Feature/sli blk traversal
AutoPas/AutoPas pull request #459
Opened 2020-05-11 06:24 UTC by Elementarereigniss

# Description

Create a 3D slice traversal, based on the described sli_blk traversal in "Algorithmic and Implementational Optimizations of Molecular Dynamics Simulations for Process Engineering" chapter 8.4, but adapted for 3 dimensional slicing.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] UnitTests
- [ ] md-flexible execution with specific yaml-file

2020-05-11 16:26 UTC, FG-TUM reviewed
- [x] needs clang-format
- [x] There seem to be many notes in the comments. Try to clean them up such that only comments remain that actually explain what you do.

2020-05-11 16:26 UTC, FG-TUM commented on src/autopas/containers/linkedCells/traversals/SlicedBlkTraversal.h
> +class SlicedBlkTraversal : public SlicedBlkBasedTraversal<ParticleCell, PairwiseFunctor, dataLayout, useNewton3>,
What's the reason for splitting this traversal in a SlicedBlkBases and the real one? Do you plan to implement further versions that work on the same base? If no merge the two files.

2020-05-25 18:26 UTC, FG-TUM commented
Before I review this please resolve the merge conflicts.

2020-08-12 15:35 UTC, FG-TUM requested changes
Please do some cleanup before I do a proper review:
- [x] remove the input files
- [x] remove debug output
- [x] condense repetitive code into loops or (lambda-)functions
- [x] remove unused code
- [ ] resolve merge conflicts from master

2020-08-12 15:35 UTC, FG-TUM commented on src/autopas/containers/cellPairTraversals/SlicedBlkBasedTraversal.h
> +  }
remove those. If they are really needed for some logging an equivalent function already exists in ArrayUtils

2020-08-12 15:35 UTC, FG-TUM commented on src/autopas/containers/cellPairTraversals/SlicedBlkBasedTraversal.h
> +          //                  z + order[2]}));
remove any commented-out code

2020-08-12 15:35 UTC, FG-TUM commented on src/autopas/containers/cellPairTraversals/SlicedBlkBasedTraversal.h
> +    if (LocksThatCanBeSet[0] && LocksThatCanBeSet[1] && LocksThatCanBeSet[2] && LocksThatCanBeSet[3] &&
to be consistent with the rest of autopas replace all `&&` with `and` and all `||` with `or`

2020-08-12 15:35 UTC, FG-TUM commented on src/autopas/containers/cellPairTraversals/SlicedBlkBasedTraversal.h
> +                                                                          i + orderCurrent[1], j + orderCurrent[2]}));
remove any debug output that is not useful for any plotting.

2020-08-12 15:35 UTC, FG-TUM commented on src/autopas/containers/cellPairTraversals/SlicedBlkBasedTraversal.h
> +        }
if you combine `x`, `y`, `z` into an array you can reduce this wall of code to a loop (might be true at other places too)

2020-08-12 15:35 UTC, FG-TUM commented on src/autopas/containers/cellPairTraversals/SlicedBlkBasedTraversal.h
> +      if (!locking2x2x2sub_blocks(m, order)) {
```suggestion
      if (not locking2x2x2sub_blocks(m, order)) {
```

2020-12-07 09:56 UTC, SteffenSeckler commented
not in a mergeable state, requires reimplementation.

2020-12-07 09:56 UTC, closed without merging