Doc and plot
AutoPas/AutoPas pull request #567
Opened 2021-01-23 14:19 UTC by FG-TUM

# Description

- [x] update documentation
- [x] clean up logging
- [x] reduce hash-map lookups
- [x] reduce number of memory allocations
- [ ] adapt / merge plot scripts

## Related Pull Requests

- #PR

## ~Resolved Issues~

# How Has This Been Tested?

- [x] existing tests

2021-01-27 13:10 UTC, SteffenSeckler approved these changes
only minor things

2021-01-27 16:23 UTC, FG-TUM commented on cmake/modules/logging.cmake
> +    target_compile_definitions(autopas PUBLIC AUTOPAS_Log_GaussianCluster)
no particular reason. Do you only want the definition / macro allcaps or also the cmake option? We are not really consistent on those anyways ¯\\\_(ツ)\_/¯

2021-01-27 16:26 UTC, SteffenSeckler commented on cmake/modules/logging.cmake
> +    target_compile_definitions(autopas PUBLIC AUTOPAS_Log_GaussianCluster)
as you prefer

2021-02-01 11:49 UTC, SteffenSeckler requested changes
the suffix should also go into the logger names, as otherwise two autopas objects cannot exist on the same process.

2021-02-01 11:49 UTC, SteffenSeckler commented on Jenkinsfile
> +                                sh "CXXFLAGS=-Wno-pass-failed CC=clang CXX=clang++ cmake -G Ninja -DCCACHE=ON -DCMAKE_BUILD_TYPE=Debug -DDAUTOPAS_LOG_ALL=ON -DAUTOPAS_ENABLE_ADDRESS_SANITIZER=ON .."
```suggestion
                                sh "CXXFLAGS=-Wno-pass-failed CC=clang CXX=clang++ cmake -G Ninja -DCCACHE=ON -DCMAKE_BUILD_TYPE=Debug -DAUTOPAS_LOG_ALL=ON -DAUTOPAS_ENABLE_ADDRESS_SANITIZER=ON .."
```

2021-02-01 11:49 UTC, SteffenSeckler commented on Jenkinsfile
> +                                sh "CXXFLAGS=-Wno-pass-failed CC=clang CXX=clang++ cmake -G Ninja -DCCACHE=ON -DCMAKE_BUILD_TYPE=Release -DDAUTOPAS_LOG_ALL=ON -DAUTOPAS_ENABLE_ADDRESS_SANITIZER=ON ..
```suggestion
                                sh "CXXFLAGS=-Wno-pass-failed CC=clang CXX=clang++ cmake -G Ninja -DCCACHE=ON -DCMAKE_BUILD_TYPE=Release -DAUTOPAS_LOG_ALL=ON -DAUTOPAS_ENABLE_ADDRESS_SANITIZER=ON .."
```

2021-02-01 11:49 UTC, SteffenSeckler commented on src/autopas/AutoPas.h
> +   * This is useful especially when multiple instances of AutoPas exist, especially in an MPI context.
```suggestion
   * This is useful when multiple instances of AutoPas exist, especially in an MPI context.
```

2021-02-01 11:49 UTC, SteffenSeckler commented on src/autopas/AutoPas.h
> +   * This is useful especially when multiple instances of AutoPas exist, especially in an MPI context.
```suggestion
   * This is useful when multiple instances of AutoPas exist, especially in an MPI context.
```

2021-02-01 11:49 UTC, SteffenSeckler commented on src/autopas/utils/logging/IterationLogger.cpp
>    // create and register a non-asychronous logger to write the header
```suggestion
  // Create and register a non-asychronous logger to write the header.
```

2021-02-01 11:49 UTC, SteffenSeckler commented on src/autopas/utils/logging/IterationLogger.h
>    static inline std::string loggerName() { return "IterationLogger"; };
suffix should go in here as well, in case we have two autopas instances on the same process

2021-02-01 16:49 UTC, SteffenSeckler commented
wow, messages from lgtm!

2021-02-01 19:09 UTC, SteffenSeckler approved these changes
good now, but doesn't compile, as _loggerName is in an ifdef, but accessed without an ifdef (in the constructor)

2021-02-01 19:09 UTC, SteffenSeckler commented on src/autopas/utils/logging/PredictionLogger.h
> +#endif
remove ifdef?

2021-02-01 19:09 UTC, SteffenSeckler commented on src/autopas/utils/logging/PredictionLogger.cpp
> +    : _loggerName("PredictionLogger" + outputSuffix) {
is not included in the ifdef => fails.

2021-02-01 19:09 UTC, SteffenSeckler commented on src/autopas/utils/logging/TuningDataLogger.h
> +#endif
remove ifdef

2021-02-01 19:09 UTC, SteffenSeckler commented on src/autopas/utils/logging/TuningResultLogger.h
> +#endif
remove ifdef

2021-02-03 09:01 UTC, merged