Progress Bar
AutoPas/AutoPas pull request #577
Opened 2021-02-17 21:22 UTC by FG-TUM

# Description

- [x] Progress bar for md-flex
- [x] additional progress info
- [x] toggleable via cli
- [x] toggleable via yaml

## ~Related Pull Requests~

## ~Resolved Issues~

# How Has This Been Tested?

- [x] Looked at the output with bar enabled
- [x] Looked at the output with bar disabled

2021-02-18 08:24 UTC, SteffenSeckler commented
can we get a screenshot?

2021-02-18 08:25 UTC, SteffenSeckler commented
fyi: some tests are failing

2021-02-18 08:28 UTC, SteffenSeckler commented on examples/md-flexible/src/Simulation.h
> +  size_t maxBarWidth = terminalWidth - info.str().size() - progressbar.str().size() - 2;
error could happen here, if `terminalWidth == 0`, i.e., no terminal was detected

2021-02-18 10:42 UTC, FG-TUM commented
> can we get a screenshot?

You and your majesty now may look at the updated description :P

2021-02-18 10:46 UTC, SteffenSeckler commented
is it possible to automatically detect if the output is not going to the terminal, but to a file? in that case, automatically disabling the progress bar would be nice :)
otherwise, the lines would be printed multiple times (see jenkins).

2021-02-18 10:52 UTC, FG-TUM commented
> is it possible to automatically detect if the output is not going to the terminal, but to a file? in that case, automatically disabling the progress bar would be nice :)
> otherwise, the lines would be printed multiple times (see jenkins).

Probably yes but tbh I can't be bothered at the moment. I would disable the output of this in jenkins via `--no-progress-bar` since it is only eye-candy anyway. However, I will add a few checks to catch errors when querying the terminal fails...

2021-02-18 12:14 UTC, SteffenSeckler commented
how about disabling it by default?

2021-02-18 12:24 UTC, FG-TUM commented
> how about disabling it by default?

The idea of md-flexible is to be a quick testing/demonstration tool. So it is primarily intended to be used manually and there the progress bar is helpful. Also if you manually need to switch it on you probably will rarely do so, however, it is no big effort to manually disable it if it causes problems.

2021-02-19 12:25 UTC, SteffenSeckler requested changes
You appear to have been influenced by https://github.com/precice/precice ;)
There is also a newline missing after the progress bar (visible after resizing the window):

![image](https://user-images.githubusercontent.com/38119442/108504301-f3364800-72b5-11eb-955e-abd19b1d032e.png)

2021-02-19 12:25 UTC, SteffenSeckler commented on examples/md-flexible/src/Simulation.h
> +                    (_config->tuningPhases.value * _config->tuningSamples.value * 30);
```suggestion
    // estimatedNumConfigs is just a random number for the number of tested configurations per tuning phase.
    size_t estimatedNumConfigs = 30;
    auto estimate = (_config->tuningPhases.value - 1) * _config->tuningInterval.value +
                    (_config->tuningPhases.value * _config->tuningSamples.value * estimatedNumConfigs);
```

30 appears to be a bit small for fullsearch (the default):
![image](https://user-images.githubusercontent.com/38119442/108503521-ce8da080-72b4-11eb-9a62-f5df9bdf4833.png)
and a bit big for bayesian-search:
![image](https://user-images.githubusercontent.com/38119442/108503755-317f3780-72b5-11eb-964a-ed8bcce33b76.png)

but, well, doesn't matter anyways...

2021-02-19 12:25 UTC, SteffenSeckler commented on examples/md-flexible/src/Simulation.h
> +    printProgress(iteration, maxIterationsEstimate, maxIterationsIsPrecice);
```suggestion
    // the last update is precise, so we know the number of iterations.
    printProgress(iteration, iteration, true);
```

2021-02-19 12:25 UTC, SteffenSeckler commented on examples/md-flexible/src/Simulation.h
> +  auto [maxIterationsEstimate, maxIterationsIsPrecice] = estimateNumIterations();
```suggestion
  auto [maxIterationsEstimate, maxIterationsIsPrecise] = estimateNumIterations();
```

2021-02-19 12:25 UTC, SteffenSeckler commented on examples/md-flexible/src/Simulation.h
> +      printProgress(iteration, maxIterationsEstimate, maxIterationsIsPrecice);
```suggestion
      printProgress(iteration, maxIterationsEstimate, maxIterationsIsPrecise);
```

2021-02-19 14:59 UTC, SteffenSeckler commented
needs formatting

2021-02-22 12:23 UTC, SteffenSeckler approved these changes
once comma

2021-02-22 12:23 UTC, SteffenSeckler commented on examples/md-flexible/src/Simulation.h
> +    // The progress bar does not end the line. Since this is the last progress bar end the line here.
```suggestion
    // The progress bar does not end the line. Since this is the last progress bar, end the line here.
```

2021-02-22 23:04 UTC, SteffenSeckler approved these changes

2021-02-23 09:17 UTC, merged