Fix r cin vcl
AutoPas/AutoPas pull request #579
Opened 2021-02-20 18:23 UTC by FG-TUM

# Description

Fixes data race when inserting particles in VCL.
- [x] turn _particlesToAdd from `vector` to `vector` of thread buffers
- [x] adapt iterators to process thread buffers in parallel
- [x] builder still takes `vector` (now of accumulated buffers)
 
## ~Related Pull Requests~

## Resolved Issues
- [ ] fixes #574

# How Has This Been Tested?

- [ ] Old unit tests
- [ ] New unit tests that test the particle buffer
- [ ] exploding liquid

2021-02-22 12:25 UTC, SteffenSeckler commented
asan detects heap-buffer-overflow

2021-03-09 15:20 UTC, FG-TUM commented
Expl liquid now works with VCL but updating the halo is excruciatingly slow...

2021-04-14 09:13 UTC, SteffenSeckler requested changes
Some things:
* change title of PR
* see comments
* some more doc for forceSequential might be good.
* maybe prevent user from using forceSequential through LogicHandler? -- is this possible with tests?

2021-04-14 09:13 UTC, SteffenSeckler commented on src/autopas/iterators/ParticleIterator.h
> + * buffers is considered arbitrary.
```suggestion
 * a halo particle if _behavior==halo). Additionally, there might be additional particle vectors that are not part
 * of the cell structure and contain arbitrary unsorted particles. These buffers result from containers that
 * have buffers they only sometimes merge with the actual data structure. Typically there is one buffer per OpenMP
 * thread, however, there is no guarantee that the iterator region has the same number of threads so the number of
 * buffers is considered arbitrary.
```

2021-04-14 09:13 UTC, SteffenSeckler commented on src/autopas/iterators/ParticleIterator.h
> +   * @param additionalVectorsToIterate Thread buffers of additional Particle Vector to iterate over.
```suggestion
   * @param additionalVectorsToIterate Thread buffers of additional Particle vector to iterate over.
```

2021-04-14 09:32 UTC, FG-TUM commented
> * change title of PR
Any suggestions? :P

> * maybe prevent user from using forceSequential through LogicHandler? -- is this possible with tests?
Why would we? If you have an iterator loop and within that region iterator you already need it and I think it is too far-fetched to say that this will never be relevant for user-code.

2021-04-14 11:33 UTC, SteffenSeckler approved these changes

2021-04-14 12:08 UTC, SteffenSeckler commented
> > * change title of PR
> 
> Any suggestions? :P
Hmm, not really. Maybe you find sth. maybe you don't, either case you can merge it.

> 
> > * maybe prevent user from using forceSequential through LogicHandler? -- is this possible with tests?
> 
> Why would we? If you have an iterator loop and within that region iterator you already need it and I think it is too far-fetched to say that this will never be relevant for user-code.
ok, convinced. is there some way to ensure that you can only use them in the inner scope?

2021-04-14 12:36 UTC, FG-TUM commented
> > > * change title of PR
> > 
> > 
> > Any suggestions? :P
> 
> Hmm, not really. Maybe you find sth. maybe you don't, either case you can merge it.

TBH the title describes pretty well what the intent and effect of the PR is. Everything else that happens here is part of other PRs which are mentioned and linked. Therefore I would leave it as it is.

> > > * maybe prevent user from using forceSequential through LogicHandler? -- is this possible with tests?
> > 
> > 
> > Why would we? If you have an iterator loop and within that region iterator you already need it and I think it is too far-fetched to say that this will never be relevant for user-code.
> 
> ok, convinced. is there some way to ensure that you can only use them in the inner scope? probably not if iterators are used, right?

Nothing simple I can think of. Anyways iterators will be replaced sooner or later so I see no point in investing much more in them.

2021-04-15 14:27 UTC, merged