Updated Contributing.md
AutoPas/AutoPas pull request #687
Opened 2022-06-07 16:20 UTC by laumeyertum

Changed the location of the funtion to new one

2022-06-09 07:17 UTC, SamNewcome approved these changes
Looks good. Cheers

2022-06-09 07:40 UTC, FG-TUM requested changes

2022-06-09 07:40 UTC, FG-TUM commented on .github/CONTRIBUTING.md
> +    lower `mpiStrategyOption`-switch.
```suggestion
  * If the new strategy handles communication between processes itself, make sure to not wrap it in the lower `mpiStrategyOption`-switch.
```
The rest of the file also leaves the line wrapping to the viewer, hence I would keep this for consistency

2022-07-20 08:02 UTC, FG-TUM approved these changes

2022-07-21 07:40 UTC, merged