Bugfix for race condition in VCL
AutoPas/AutoPas pull request #760
Opened 2023-06-24 14:29 UTC by dmartin13

# Description

It looks like the problem came from the fact that we called `particlesToAddEmpty()` in iterations with invalid container status. However, in these iterations `_particlesToAdd` is used by multiple threads, which is why races can occur. In this version, we solve this by calling `particlesToAddEmpty()` only when the container state is valid, to ensure that we don't have particles in the buffer during these iterations:

```
if (_isValid != ValidityState::invalid) {
// This section ensures that we do not have particles in _particlesToAdd when the container status is valid. 
// In this case we don't need to concatenate the buffers, we can just pass the additionalVectors.
      if (not particlesToAddEmpty()) {
        autopas::utils::ExceptionHandler::exception(
            "VerletClusterLists::begin(): Error: particle container is valid, but _particlesToAdd isn't empty!");
      }
      // If the particles are sorted into the towers, we can simply use the iteration over towers.
      return ContainerIterator<Particle, true, false>(*this, behavior, additionalVectors);
    } else {
    // In this case (invalid status) we concatenate additionalVectors and _particlesToAdd if additionalVectors contain particles, otherwise we just pass _particlesToAdd
 }
```

The variant to check only the buffers of the respective thread in `particlesToAddEmpty()` was tested, however, also this led to race-conditions. The problem is that the functions `begin() const`, `getRegionIterator()` and `getRegionIterator() const` are always called only by thread 0. For testing, I included an exception that throws when a thread other than T0 executes the function and used it to run example simulations (fallingDrop and explodingLiquid using only VCL), which resulted in no exception. For this reason, in `begin()` and `getRegionIterator()` we need to check all buffers in `_particlesToAdd` to see if there really are no particles in it

## Related Pull Requests

- https://github.com/AutoPas/AutoPas/pull/742

## Resolved Issues

- [x] fixes #756
- [x] fixes #755

# How Has This Been Tested?
- All existing tests with current master ([8299124](https://github.com/AutoPas/AutoPas/commit/829912490c798c2eff623e9da1f645ed8b97754e) )
- All tests that failed in https://github.com/AutoPas/AutoPas/commit/3df9b768a61b8217682bc329ef757b2c80327007 with Thread Sanitizers enabled using the docker container with following command:
(tested for https://github.com/AutoPas/AutoPas/commit/3df9b768a61b8217682bc329ef757b2c80327007 and current master [8299124](https://github.com/AutoPas/AutoPas/commit/829912490c798c2eff623e9da1f645ed8b97754e))
```
docker run -v ${PathToAutoPasRoot}:/autopas -it autopas/autopas-build-archer \
bash -c "export TSAN_OPTIONS=ignore_noninstrumented_modules=1 && cd /autopas/build
CC=clang CXX=clang++ cmake \
  -G Ninja \
  -DCCACHE=ON \
  -DCMAKE_BUILD_TYPE=Release \
  -DAUTOPAS_LOG_ALL=ON \
  -DAUTOPAS_OPENMP=ON \
  -DAUTOPAS_ENABLE_ADDRESS_SANITIZER=OFF \
  -DAUTOPAS_ENABLE_THREAD_SANITIZER=ON \
  -DAUTOPAS_INTERNODE_TUNING=OFF \
  -DMD_FLEXIBLE_USE_MPI=OFF \
  -DMD_FLEXIBLE_FUNCTOR_AUTOVEC=ON \
  -DMD_FLEXIBLE_FUNCTOR_AUTOVEC_GLOBALS=OFF \
  -DMD_FLEXIBLE_FUNCTOR_AVX=ON \
  -DMD_FLEXIBLE_FUNCTOR_SVE=OFF \
  -DAUTOPAS_ENABLE_ALLLBL=OFF \
  .. \
  && ninja runTests \
  && ctest --output-on-failure -R '^testAutopas\/Generated\/ContainerIteratorTest\.deleteParticles\/VerletClusterLists'"
```
- Example simulations (fallingDrop only with VCL and different boundary-conditions): The number of (owned) particles at the end was identical to the number at the beginning.

2023-06-26 09:04 UTC, FG-TUM requested changes
Ok so just for me to understand why this works: You only call `particlesToAddEmpty()` when `_isValid != ValidityState::invalid` as a sanity check because if the container is valid, these vectors are always empty. If the state is valid you always add the vectors and never call `particlesToAddEmpty()`, thus never reading and writing at the same time.
Did I get that right?

2023-06-26 13:05 UTC, dmartin13 commented on src/autopas/containers/verletClusterLists/VerletClusterLists.h
> -  }
Yes

2023-07-02 09:11 UTC, dmartin13 commented
> > The problem is that the functions begin() const, getRegionIterator() and getRegionIterator() const are always called only by thread 0.
> 
> I'm not so sure about that 🙃. Afaik, md-flex just doesn't ever use the `const` iterators. Also, the non-`const` of `getRegionIterator()` should be called from `RegularGridDecomposition::exchangeHaloParticles()`->`AutoPas::addHaloParticles()` which has a parallel section around the loop. Throw some new loop somewhere into md-flex over a `const auto &autoPasConst = autoPas` then you use the `const` iterators (you won't be able to `++iter`) and then look for your exceptions again. Also, make sure with `cout` or breakpoints that you really come by the functions you expect.

Yes, I agree.

2023-07-02 19:34 UTC, dmartin13 commented
> Ok so just for me to understand why this works: You only call `particlesToAddEmpty()` when `_isValid != ValidityState::invalid` as a sanity check because if the container is valid, these vectors are always empty. If the state is valid you always add the vectors and never call `particlesToAddEmpty()`, thus never reading and writing at the same time. Did I get that right?
> 
> But in the end, this only works, because coincidentally, we never modify _particlesToAdd() during any iteration in md-flex. This is dangerous, because we read the size of this vector.

Yes, this was added as a sanity check. In the new version in [a947a5f](https://github.com/AutoPas/AutoPas/pull/760/commits/a947a5fd19c1c7a83bc88e77511023e476fd0901) `_particlesToAdd` is only checked for emptiness for the respective thread's buffer. Thus we should not run into problems regarding races.

2023-07-03 09:00 UTC, FG-TUM reviewed
Just one final suggestion :upside_down_face:

2023-07-03 13:19 UTC, dmartin13 commented on src/autopas/containers/verletClusterLists/VerletClusterLists.h
>    }
I agree, this version looks much cleaner. The problem I have with merging is that I call once from a `const` function and once not.  So far I haven't figured out how to have only one version for both calls. Are there any possibilities? I can only think of a `const_cast` that might work.

2023-07-03 13:33 UTC, FG-TUM commented on src/autopas/containers/verletClusterLists/VerletClusterLists.h
>    }
Ah, sorry I overlooked that one of the versions was really `const`.

[CppCoreGuidelines to the rescue!](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es50-dont-cast-away-const)

They actually show a "not great" and a "good" solution. Pick whichever you want. I'm fine with either ;)

2023-07-04 15:27 UTC, FG-TUM approved these changes

2023-07-04 15:27 UTC, merged