Fix Configs Generator Script
AutoPas/AutoPas pull request #923
Opened 2024-07-29 11:17 UTC by FG-TUM

# Description

The Python script that was used to generate a wide range of testcases for MD flexible used an outdated config template.

- [x] Fix/Update template
- [x] Change defaults to something slightly more reasonable

## ~Related Pull Requests~

## ~Resolved Issues~

# How Has This Been Tested?

- [x] Ran all generated configs successfully

2025-01-30 08:35 UTC, SamNewcome requested changes
Some changes:

- Warnings that the exclusion criteria may not be appropriate
- Changes that reflect the current dynamic rebuilding master

Related to the last point:
I think the `skinFactor` and `invMaxParticleSpeed` stuff is a bit confusing (even ignoring dynamic rebuilding). I would simply make the `skinFactor` a factor of the cutoff, which is a bit more common of a terminology. Then I would keep rebuild frequency fixed as 100. This is not so suitable but I don't know of something better to have here: with dynamic rebuilding, these "static" (dt=0) experiments become a little misleading, but this is a subject of ongoing research and I don't care about it here.

2025-01-30 08:35 UTC, SamNewcome commented on examples/md-flexible/scripts/generate-mdflex-configs.py
> +verlet-skin-radius-per-timestep  :  0.0075
I think this is now out of date for the master

2025-01-30 08:35 UTC, SamNewcome commented on examples/md-flexible/scripts/generate-mdflex-configs.py
> +    data['verlet-skin-radius-per-timestep'] = skin / rebuildFrequency
Similar to above comment

2025-01-30 08:35 UTC, SamNewcome commented on examples/md-flexible/scripts/generate-mdflex-configs.py
> +    # Exclusion rules. Mostly to avoid scenarios that take forever to test.
This is a slightly awkward one. These parameters would exclude some of the current test cases which I am working on. But whilst I could suggest values which are more appropriate for my current test cases, these values could easily become as inappropriate in the future as these are for my test cases. My suggestion is to leave these as they are but add the warning:

```suggestion
    # Exclusion rules. Mostly to avoid scenarios that take forever to test. Warning: These parameters may not be appropriate for your test cases.
```

2025-01-30 08:35 UTC, SamNewcome commented on examples/md-flexible/scripts/generate-mdflex-configs.py
> +numbers in tiny domains.
See my comment on line 202 for my reasoning for this:

```suggestion
It is not simply the cross product of the range of parameters below,
but also tries to exclude unfeasible combinations, e.g. huge particle
numbers in tiny domains.

These exclusion criteria may not be appropriate for your test cases.
E.g. they assume a sigma of no smaller than one and a cutoff of no 
larger than 3.
```
(Potentially replace the assumption with whatever is more appropriate)

2025-03-26 23:42 UTC, FG-TUM commented on examples/md-flexible/scripts/generate-mdflex-configs.py
> +    data['verlet-skin-radius-per-timestep'] = skin / rebuildFrequency
-> 630a150

2025-03-26 23:42 UTC, FG-TUM commented on examples/md-flexible/scripts/generate-mdflex-configs.py
> +verlet-skin-radius-per-timestep  :  0.0075
-> 630a150

2026-08-27 14:22 UTC, thesamriel commented
Sorry, but we will just get rid of scripts in the repo entirely. See #1177

2026-08-27 14:22 UTC, closed without merging