Functorless Neighborlist Rebuild for VLC
AutoPas/AutoPas pull request #945
Opened 2024-09-10 08:18 UTC by dmartin13

# Description

In this PR, the neighborlist rebuild is modified so that they work without functors.

## TODO
- [x] vlc_c18
- [ ] vlp_c01
- [ ] vlp_c08
- [ ] vlp_c18

## Resolved Issues

- [ ] fixes #878

# How Has This Been Tested?

- [ ] Existing Tests
- [ ] The coverage report shows all relevant lines are tested.

2025-03-13 10:21 UTC, SamNewcome commented
> In most cases, the efficiency is increased by the new rebuild. In some cases, however, it seems to be slower. This seems to be mainly the case for VLC, SoA with newton3 disabled and has not been further investigated yet. For the VLP traversals, a clear increase in performance can be seen. This could also have to do with the fact that a data structure that maps cell IDs was omitted and replaced by a lambda.

> The tests were run with 8 HW threads on a Xeon E5-2650 v2.
> "New" corresponds to [842ce57](https://github.com/AutoPas/AutoPas/pull/945/commits/842ce57c27abdad3209092d680dc5ec347bdd653)
> "Old" corresponds to https://github.com/AutoPas/AutoPas/commit/15a704855b96c3416f5e03df0256c6c1572872bf
> [plot.pdf](https://github.com/user-attachments/files/18829893/plot.pdf)

It looks like the only cases where it is slower are for configurations where newton3 enabled is possible and faster - so I don't think this is a signficant issue.

2025-03-13 16:04 UTC, SamNewcome requested changes
Looks good. I have no major issues, just comments, variable names, and an unused function.

2025-04-19 13:09 UTC, dmartin13 commented on src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCCellPairC08CellHandler.h
> -      if (cell2Local != globalToLocalIndex[offsetCell1].end()) {
In `buildAoSNeighborList` in VLCCellPairNeighborLists.h it is ensured that there are 27 lists for the neighbors for each cell. The offsets are only calculated for direct neighbors. This means 27, so there should be no errors here. But to be on the safe side, we could also insert it again.

2025-04-22 09:26 UTC, dmartin13 commented on src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCCellPairNeighborList.h
> +      }
Good catch! The strange second if statement comes from a version when I was still doing a very rudimentary test of inserting the particles into the neighbor lists. Now it is no longer necessary.
That's right! Everything above “If true, we loop over the partner cells again” can be answered with yes.

2025-04-22 12:51 UTC, dmartin13 commented on src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCAllCellsNeighborList.h
> +        // Go over all cells except the very last layer and create lists per base step.
To be honest, I'm not quite sure why this is necessary for C08. Or to be precise: I'm not quite sure why omitting the last layer doesn't result in an error. The C08 rebuild was the first functorless rebuild and was already implemented. I think @schuhmaj  wrote it. Maybe he knows more about it. I adapted it for all other traversals.
If you look at the following figure and imagine you leave out the last layer. What happens then, for example, with the interactions between cells 14 and 19? But I must be missing something, because all traversal comparison tests pass.
![Bildschirmfoto von 2025-04-22 14-48-57](https://github.com/user-attachments/assets/49d56cc2-18a1-455d-9ec5-deef99bb924f)

2025-04-22 12:54 UTC, dmartin13 commented on src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCCellPairNeighborList.h
> +                  // list
done in [8e7f482](https://github.com/AutoPas/AutoPas/pull/945/commits/8e7f482a36a975e62b65b30b2bc0653c38a8b9e6)
I have added an extra sentence

2025-04-22 12:54 UTC, dmartin13 commented on src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCCellPairNeighborList.h
> +                startIndexCell2 = particleIndexCell1 + 1;
done in [8e7f482](https://github.com/AutoPas/AutoPas/pull/945/commits/8e7f482a36a975e62b65b30b2bc0653c38a8b9e6)

2025-04-22 12:55 UTC, dmartin13 commented on src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCAllCellsNeighborList.h
> +                  // If the traversal does not use Newton3 the inverse interaction also needs to be stored in p2's list
done in [8e7f482](https://github.com/AutoPas/AutoPas/pull/945/commits/8e7f482a36a975e62b65b30b2bc0653c38a8b9e6)

2025-04-22 12:55 UTC, dmartin13 commented on src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCAllCellsNeighborList.h
> +                startIndexCell2 = particleIndexCell1 + 1;
done in [8e7f482](https://github.com/AutoPas/AutoPas/pull/945/commits/8e7f482a36a975e62b65b30b2bc0653c38a8b9e6)

2025-04-22 12:55 UTC, dmartin13 commented on src/autopas/containers/verletListsCellBased/verletListsCells/VerletListsCells.h
> +  void rebuildNeighborListsVLC(TraversalOption traversal) {
done in [8e7f482](https://github.com/AutoPas/AutoPas/pull/945/commits/8e7f482a36a975e62b65b30b2bc0653c38a8b9e6)

2025-05-07 08:33 UTC, SamNewcome commented on src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCAllCellsNeighborList.h
> +        // Go over all cells except the very last layer and create lists per base step.
I _think_ this is because we include halo cell in `cellsPerDim`. Therefore, the last layer will be halo cells. We do not need neighbour lists between halo particles, only owned-halo interactions, so we don't need to generate lists e.g. between 14 and 19 if they are both halo cells. In the c08 base step, the interactions are "forward-looking", so if the base cell is halo, all cells within the base step will also be halo cells. For C01 and C18, there are some "backward-looking" interactions, so we still need to include base steps with base cells that are halo cells.

That being said, lines 202-206 mean that we don't do any calculations to determine neighbour lists between halo cells but, as we still reserve memory for neighbour lists, I think it is still beneficial to skip these halo base cells in the C08 case.

Please check this logic - I am not 100% sure.

Fyi, I think it was @FG-TUM who wrote this.

2025-05-07 08:44 UTC, SamNewcome commented on src/autopas/containers/verletListsCellBased/verletListsCells/traversals/VLCCellPairC08CellHandler.h
> -      if (cell2Local != globalToLocalIndex[offsetCell1].end()) {
No I think this is fine.

2025-05-07 08:59 UTC, SamNewcome requested changes
This is all good except two deleted files have creeped back in (I think due to the merge from `master`).

2025-05-07 08:59 UTC, SamNewcome commented on src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCAllCellsGeneratorFunctor.h
I think this file was accidentally added due to a merge

2025-05-07 08:59 UTC, SamNewcome commented on src/autopas/containers/verletListsCellBased/verletListsCells/neighborLists/VLCCellPairGeneratorFunctor.h
Again, I think the re-addition of this file was a merging mistake

2025-05-12 07:23 UTC, SamNewcome approved these changes
Looks good!

2025-05-22 15:29 UTC, merged