Highway clone based
AutoPas/AutoPas pull request #972
Opened 2024-11-17 17:57 UTC by TumBeat

# Description

This PR introduces the Google-Highway Lennard Jones Functor and a different particle interaction orders (vectorization patterns) for the SoAPair and SoASingle Functor methods.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [ ] Implemented Unit Tests for Highway vs. AVX
- [ ] Implemented Unit Tests for the various patterns vs. AVX

2025-11-24 09:50 UTC, thesamriel requested changes
I had a couple of small things in the functor file, where I took the liberty to edit these directly.
There's a couple more minor things.

Lastly, we might want to discuss if we really merge all input yaml files or if we keep them somewhere separate.

2025-11-24 09:50 UTC, thesamriel commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorAVXTest.cpp
> +    particle.setTypeId(particle.getID() % 5);
Is this line supposed to be here? If so, the  `if constexpr (mixing)` can be removed.

2025-11-24 09:50 UTC, thesamriel commented on cmake/modules/autopas_highway.cmake
> +    URL ${AUTOPAS_SOURCE_DIR}/libs/highway-1.2.0.zip
The latest version of highway seems to be 1.3.0. If there are no  compatibility problems with the current functor implementation, I would already switch to the latest version

2025-11-24 09:50 UTC, thesamriel commented on examples/md-flexible/src/configuration/MDFlexConfig.h
> +                                                      FunctorOption::lj12_6_AVX, "functor", true,
Probably want to keep this at `none`

2025-11-24 09:50 UTC, thesamriel commented on libs/highway-master.zip
I think this version is not used, so we can remove it

2025-11-24 09:50 UTC, thesamriel commented on examples/md-flexible/CMakeLists.txt
> +option(MD_FLEXIBLE_FUNCTOR_HWY "If instruction set is available, compile Highway Functor." ON)
I think if no instruction set is available, highway falls back to normal scalar instructions.
```suggestion
option(MD_FLEXIBLE_FUNCTOR_HWY "Compile Highway Functor, which uses the best available SIMD instruction set supported by google highway." ON)
```

2025-11-24 09:50 UTC, thesamriel commented on examples/md-flexible/src/configuration/YamlParser.cpp
> +        } else if (strArg.find("highway") != std::string::npos) {
```suggestion
        } else if (strArg.find("hwy") != std::string::npos or strArg.find("highway") != std::string::npos) {
```

2025-11-24 09:50 UTC, thesamriel commented on examples/md-flexible/src/configuration/CLIParser.cpp
> +        } else if (strArg.find("highway") != string::npos) {
```suggestion
        } else if (strArg.fing("hwy") != string::npos or strArg.find("highway") != string::npos) {
```

2025-11-24 09:50 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +
```suggestion
```

2025-11-24 09:50 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      SoAFunctorSingleImpl<true, VectorizationPattern::p1xVec>(soa);
`SoAFunctorSingleImpl` is only called with the vectorization pattern `p1xVec`, as far as I can tell. If true, then I would remove it as a function template

2025-11-24 09:50 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * @tparam newton3 Whether to use newton3 (TODO: compare with other functors)
Is this an open todo or smth we can delete?

2025-11-24 09:50 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    for (; checkFirstLoopCondition<true, vecPattern>(i, 0); decrementFirstLoop<vecPattern>(i)) {
I noticed smth interesting here.
`i` is of type `size_t` and gets decremented every iteration until it reaches 0. In the next call to `decrementFirstLoop`, `i` is decremented again, which leads to a wrap around and `i` being the maximum unsigned long number. Then, in `checkFirstLoopCondition` it is implicitly converted to a `signed long` value, which in most implementations leads to a negative number and therefore to `i >= 0`  being false. However, this is actually undefined behavior, and we should solve this differently. 
Easiest option would be to make `i` a signed integer. Otherwise, the loop conditions would need to be handled differently.

2025-11-24 16:05 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      SoAFunctorSingleImpl<true, VectorizationPattern::p1xVec>(soa);
That can be removed. I just clarified that with Luis.

2025-11-24 16:06 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * @tparam newton3 Whether to use newton3 (TODO: compare with other functors)
I think it can be removed. newton3 is only relevant for globals in `SoAFunctorSingle`.

2025-11-24 16:18 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorAVXTest.cpp
> +    particle.setTypeId(particle.getID() % 5);
That looks like a leftover. In all other similar tests, this extra line does not exist.

2025-11-24 16:18 UTC, dmartin13 commented on cmake/modules/autopas_highway.cmake
> +    URL ${AUTOPAS_SOURCE_DIR}/libs/highway-1.2.0.zip
Changed to 1.3.0.

2025-11-24 16:19 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    for (; checkFirstLoopCondition<true, vecPattern>(i, 0); decrementFirstLoop<vecPattern>(i)) {
Good catch! I have modified this slightly and now use a `std::ptrdiff_t`, which can also be negative.

2025-12-03 13:09 UTC, SamNewcome requested changes
There are some performance related suggestions. Imo, these aren't critical and don't have to be done this PR. We have our AutoPas internal meeting on Friday so I might discuss this with @thesamriel then, whether we want you to investigate this. For now, it would be good if you at least comment with your views on if you think they are good ideas, or meh, you think they are not worth investigating, or you don't know - don't spend too much time researching, just if your previous experience suggests something.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +using MaskLong = decltype(highway::FirstN(tag_long, 2));
It would be good if we had some kind of "highway utils" file, so this can be shared. Plus, I feel a little uncomfortable about the `namespace highway = hwy::HWY_NAMESPACE;` getting included everywhere this header get included - I am fine if this is rather upfront i.e. every file in the application library/example simulator is okay with being "contaminated" by this namespace alias.

I don't have a strong opinion right now about whether this should be in AutoPas or in the application library. Imo, the argument for putting this in AutoPas, is that it would be really nice if we could avoid users have to write such ugly functors with effectively lots of boilerplate code by providing a class (i.e. in AutoPas src) which implements all the boilerplate stuff such that the specific functors only need to implement the kernel. But right now, there's no real need for this.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  using SoAArraysType = typename Particle_T::SoAArraysType;
```suggestion
  using SoAArraysType = Particle_T::SoAArraysType;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  }
I know we don't do this elsewhere, but we should change `_PPLibrary` from a raw pointer to an optional reference (`std::optional<std::reference_wrapper<ParticlePropertiesLibrary>>`). Then we (A) get rid of the (raw) pointer and (B) I think we only then need one constructor.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        break;
Add an exception

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  constexpr bool checkFirstLoopCondition(const long i, const long stop) {
Add some documentation. Do this for all the functions with missing documentation.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  constexpr bool checkFirstLoopCondition(const long i, const long stop) {
I also don't like the variable name `stop`. Maybe `vecEnd`?

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  constexpr bool checkFirstLoopCondition(const long i, const long stop) {
We should also rewrite this in a more readable way. I dislike the mixing of the ternary operator and if `constexpr` `if` statements - we should stick with one.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        const long criterion = stop - _vecLengthDouble / 2 + 1;
Add a comment about switching to signed `long` to avoid integer underflows

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  constexpr bool checkFirstLoopCondition(const long i, const long stop) {
Consider also making first doing `if constexpr (reversed)` and then inside that the different vector patterns: in my mind this is a nicer grouping.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        const long criterion = stop - _vecLengthDouble / 2 + 1;
Add also that the narrowing conversion of `_vecLengthDouble` shouldn't cause issues as it is not expected to be so large.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  constexpr int obtainFirstLoopRest(const int i, const int stop) {
Try to come up with a better name. Otherwise I will settle for documentation

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      int64_t owned = static_cast<int64_t>(ownedStatePtr[i]);
```suggestion
      const auto owned = static_cast<int64_t>(ownedStatePtr[i]);
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +                             VectorDouble &y1, VectorDouble &z1, MaskDouble &ownedMaskI, const size_t restI) {
For the `ownedMaskI`, we first take the `ownedStatePtr`, cast it to `int64_t`, then convert it to `double`, and then check that it is not equal to zero. Could we simply just cast it to `int64_t` and then check that it is not equal to zero directly?

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        int64_t ownedSecond = static_cast<int64_t>(ownedStatePtr[index]);
```suggestion
        const auto ownedSecond = static_cast<int64_t>(ownedStatePtr[index]);
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
There are times we use `LoadN` instead of a masked load - do you think changing this would help?

Alternatively, would aligned loads be worth the effort?

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      int index = reversed ? (remainder ? 0 : i - _vecLengthDouble + 1) : i;
```suggestion
      const auto index = reversed ? (remainder ? 0 : i - _vecLengthDouble + 1) : i;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      if constexpr (!remainder) {
```suggestion
      if constexpr (not remainder) {
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      fz2Ptr[j] -= highway::ReduceSum(tag_double, lowerFzExt);
An alternative way of writing this would be with a `MaskedReduceSum` with a mask with the upper half masked out (if in the remainder case, without padding with zeros, union this with the `mask` on line 489). 

This reduces these 3/4 operations to one, improving readability. I suspect that this may even be more performant, or at least no less performant - my understanding of `MaskedReduceSum` (at least for AVX512) is that it is basically creating a version of `fx` with masked out lanes with zeros and then applying the regular `ReduceSum`. So I suspect that this is faster.

I would quite like this investigated - doesn't have to be super thorough, just make sure we aren't shooting ourselves in the foot with this change.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        fz2Ptr[j + 1] -= highway::ReduceSum(tag_double, upperFzExt);
Similar

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        int index = reversed ? i - 1 : i + 1;
```suggestion
        const auto index = reversed ? i - 1 : i + 1;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      if constexpr (!remainder) {
```suggestion
      if constexpr (not remainder) {
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      fzPtr[i] += highway::ReduceSum(tag_double, lowerFzAccExt);
This is potentially similar to as discussed in `handleNewton3Reduction`, but I'm less confident that `MaskedReduceSum` is faster. Even if it were the same speed though, I would prefer it as we reduce from three operations to one (i.e. simpler code)

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        fzPtr[index] += highway::ReduceSum(tag_double, upperFzAccExt);
Similar

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    double globals[4]{highway::ReduceSum(tag_double, virialSumX), highway::ReduceSum(tag_double, virialSumY),
As far as I am aware, there is no reason this couldn't be a C++ style array

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    double globals[4]{highway::ReduceSum(tag_double, virialSumX), highway::ReduceSum(tag_double, virialSumY),
And `const`

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    }
```suggestion
    const double factor = newton3 ? 0.5 : 1.;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    for (; checkFirstLoopCondition<true, VectorizationPattern::p1xVec>(i, 0);
```suggestion
    for (std::ptrdiff_t i = static_cast<std::ptrdiff_t>(soa.size()) - 1; checkFirstLoopCondition<true, VectorizationPattern::p1xVec>(i, 0);
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      VectorLong ownedStateJ = highway::Set(tag_long, static_cast<int64_t>(ownedStatePtr2[j]));
```suggestion
      VectorLong ownedStateJ = highway::Set(tag_long, ownedStatePtr2[j]);
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  inline void fillJRegisters(const size_t j, const double *const __restrict x2Ptr, const double *const __restrict y2Ptr,
Similarly to `fillIRegisters`, I don't think the conversion of owned state to `double` is necessary.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        const auto tmpOwnedJ = highway::Set(tag_long, static_cast<int64_t>(ownedStatePtr2[j + 1]));
```suggestion
        const auto tmpOwnedJ = highway::Set(tag_long, ownedStatePtr2[j + 1]);
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      for (int n = 0; n < (remainderJ ? restJ : _vecLengthDouble); ++n) {
`n` -> `j`

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        for (int k = 0; k < (remainderJ ? restJ : _vecLengthDouble / 2); ++k) {
`k` -> `j`

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +          int index = i * (_vecLengthDouble / 2) + k;
```suggestion
          const auto index = i * (_vecLengthDouble / 2) + k;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +          auto typeID1 = reversed ? typeID1Ptr - i : typeID1Ptr + i;
```suggestion
          const auto typeID1 = reversed ? typeID1Ptr - i : typeID1Ptr + i;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        for (int k = 0; k < (remainderJ ? 1 : 2); ++k) {
`k` -> `j`

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +          int index = i + _vecLengthDouble / 2 * k;
```suggestion
          const auto index = i + _vecLengthDouble / 2 * k;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +          auto typeID1 = reversed ? typeID1Ptr - i : typeID1Ptr + i;
```suggestion
          const auto typeID1 = reversed ? typeID1Ptr - i : typeID1Ptr + i;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      for (int n = 0; n < (remainderI ? restI : _vecLengthDouble); ++n) {
`n` -> `i`

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    // alignas(64) std::array<autopas::OwnershipState, _vecLengthDouble> ownedStates2Tmp{};
Remove the deadcode

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +                        const unsigned int restI, const unsigned int restJ) {
I think there's scope for optimisation here, at least for AVX512. With AVX512, masked operations appear to be as fast as unmasked operations, so it doesn't make sense to separately determine `facMasked`, you can determine `fx` (and similar) directly using a masked multiply. With other architectures, I believe this becomes a separate apply mask and then multiply (so in these cases no faster). This holds similarly in the `calculateGlobals`.

I also believe you can get higher performance on AVX512 by using fused multiply adds (`highway::MulAdd` or the masked version). Again, on e.g. AVX2 this won't help, but it should on AVX512.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  inline void fillPhysicsRegisters(const size_t *const typeID1Ptr, const size_t *const typeID2Ptr,
This function could be optimised (probably) by using Gather functions, instead of constructing the arrays scalar-ly,

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    for (; j < (neighborList.size() & ~(_vecLengthDouble - 1)); j += _vecLengthDouble) {
This `j < (neighborList.size() & ~(_vecLengthDouble - 1))` is quite ugly and should be changed, or explained.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  /* TODO: compare with other functors */
This should be removed - I guess this was just a note to double check that this looks the same as with other functors? In which case, double check and remove.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  void endTraversal(bool newton3) final {
```suggestion
  void endTraversal(const bool newton3) final {
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  void setParticleProperties(double epsilon24, double sigmaSquare) {
```suggestion
  void setParticleProperties(const double epsilon24, const double sigmaSquare) {
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      _shift6AoS = ParticlePropertiesLibrary<double, size_t>::calcShift6(epsilon24, sigmaSquare, _cutoffSquareAoS);
```suggestion
      _shift6AoS = ParticlePropertiesLibrary::calcShift6(epsilon24, sigmaSquare, _cutoffSquareAoS);
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      _shift6 = highway::Set(tag_double, ParticlePropertiesLibrary<double, size_t>::calcShift6(
```suggestion
      _shift6 = highway::Set(tag_double, ParticlePropertiesLibrary::calcShift6(
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  MaskDouble equalMasks[_vecLengthDouble / 2];
This doesn't seem to ever be used -> remove

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  VectorizationPattern _vecPattern;
Add brief documentation for all of these

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.h
> +  LJFunctorTestHWY() : AutoPasTestBase() {}
```suggestion
  LJFunctorTestHWY() {}
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.h
> +                                                   (_cutoff + _skinPerTimestep * _rebuildFrequency)};
Merge `_skinPerTimestep` and `_rebuildFrequency` to `_skin`, as we don't have a per timestep skin anymore

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.h
Add documentation

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.h
> +  bool particleEqual(Molecule &p1, Molecule &p2);
Rename these to include a verb. E.g. `checkParticlesAreEqual`

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> + * @date 04/23/24
Switch this to DD/MM/YYYY

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.h
> + * @date 04/23/24
-> DD/MM/YYYY

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +    double tolerance = 2e-8;
```suggestion
    constexpr double tolerance = 2e-8;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +    double tolerance = 2e-8;
Also, this tolerance feels concerningly high. Try a stricter tolerance.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  // clang-format on
```suggestion
  return not HasFailure();
```
The return type is indented more than normal. I don't really get why? Unless you can think of a reason, we can keep it normally indented and then remove the turn off and on clang-format comments.

Also `::testing::Test::` isn't needed.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.h
> +  bool particleEqual(Molecule &p1, Molecule &p2);
Also, the arguments can be `const`

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +bool LJFunctorTestHWY::AoSParticlesEqual(FMCell &cell1, FMCell &cell2) {
`ret` is never used. Remove it and the redundant return statement

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  return counter == 0;
Change the counter to a simple flag, which is the union of all the `not particleEqual(...)` calls.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.h
> +  void testLJFunctorAVXvsLJFunctorHWYAoS(bool newton3, bool doDeleteSomeParticles);
The arguments of these could be made `const`

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  size_t numParticles = 23;
```suggestion
  const size_t numParticles = 23;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  ParticlePropertiesLibrary<double, size_t> PPL{_cutoff};
```suggestion
  ParticlePropertiesLibrary PPL{_cutoff};
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +    PPL.calculateMixingCoefficients();
Make the LJ parameters more different from each other

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  Molecule defaultParticle({0, 0, 0}, {0, 0, 0}, 0, 0);
```suggestion
  const Molecule defaultParticle({0, 0, 0}, {0, 0, 0}, 0, 0);
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +      if (particle.getID() == 12) autopas::internal::markParticleAsDeleted(particle);
These particle IDs are arbitrary, right? It would be good commenting this

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
These tests should compare against the AutoVec functor instead of the AVX functor, otherwise our testing framework for the functor is not as portable as the functor.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  ASSERT_TRUE(AoSParticlesEqual(cell2HWY, cell2NoHWY)) << "Cells 2 not equal after copy initialization.";
I kinda get wanting each "stage" to have an `ASSERT`, as if e.g. the copying is wrong, the other steps will probably be wrong. But we probably still want both checks at each step to print errors at least. 

Make everything `EXPECT`. If you want to keep this `ASSERT` behaviour, somehow get the test to stop after the two `EXPECT`s. But I don't mind whether or not you do this.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +      << "Cells 2 not equal after loading.";
Similar

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +      << "Cells 2 not equal after applying functor.";
Similar

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  ASSERT_TRUE(AoSParticlesEqual(cell2HWY, cell2NoHWY)) << "Cells 2 not equal after extracting.";
Similar

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  // EXPECT_NEAR(ljFunctorAVX.getVirial(), ljFunctorHWY.getVirial(), tolerance) << "global virial";
Uncomment these

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  double tolerance = 1e-8;
Make the `tolerance` `constexpr`. Also, I try a lower tolerance - I'm a little suspicious of it being too high.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  size_t numParticles = 23;
```suggestion
  const size_t numParticles = 23;
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +    PPL.calculateMixingCoefficients();
Make the parameters more different. Potentially, just make the PPL part of the test class, and then we don't need this duplicate code.

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  Molecule defaultParticle({0, 0, 0}, {0, 0, 0}, 0, 0);
```suggestion
  const Molecule defaultParticle({0, 0, 0}, {0, 0, 0}, 0, 0);
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  ASSERT_TRUE(AoSParticlesEqual(cellHWY, cellNoHWY)) << "Cells 1 not equal after extracting.";
Remove `1` from message

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  // EXPECT_NEAR(ljFunctorAVX.getVirial(), ljFunctorHWY.getVirial(), tolerance) << "global virial";
Similar

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  }
Similar

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  Molecule defaultParticle({0, 0, 0}, {0, 0, 0}, 0, 0);
```suggestion
  const Molecule defaultParticle({0, 0, 0}, {0, 0, 0}, 0, 0);
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  constexpr bool calculateGlobals = true;
```suggestion
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  // EXPECT_NEAR(ljFunctorAVX.getVirial(), ljFunctorHWY.getVirial(), tolerance) << "global virial";
Similar

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  }
Similar

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  Molecule defaultParticle({0, 0, 0}, {0, 0, 0}, 0, 0);
```suggestion
  const Molecule defaultParticle({0, 0, 0}, {0, 0, 0}, 0, 0);
```

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  // EXPECT_NEAR(ljFunctorHWY.getVirial(), ljFunctorAVX.getVirial(), tolerance) << "global virial";
Similar

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
Add brief comment descirptions above each test

2025-12-03 13:09 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +
Rather than having a `vector` of pattern _values_ and then a map to turn them to string, just have a `vector` of `VectorizationPatternOption`s, which includes a conversion to string functionality.

I am just talking about the test and not necessarily the functor (so at some point you need to just get the option's value to pass to the functor).

2025-12-03 13:09 UTC, SamNewcome commented on libs/CMakeLists.txt
> +include(autopas_highway)
Potentially my most pedantic code review comment ever: I am mildly triggered that this isn't grouped together with the other `include(...)`s.

2025-12-03 13:09 UTC, SamNewcome commented on src/autopas/tuning/utils/SearchSpaceGenerators.h
> +                                         const std::set<VectorizationPatternOption> &allowedVecPatternOptions);
Rather pedantic, but I would prefer this grouped with the other "allowed...Options" arguments i.e. before `interactionType`

2025-12-03 13:09 UTC, SamNewcome commented on src/autopas/baseFunctors/Functor.h
> +   * Setter for the vectorization pattern to choose
```suggestion
   * Setter for the vectorization pattern to be used.
```

2025-12-03 13:09 UTC, SamNewcome commented on src/autopas/options/VectorizationPatternOption.h
> + * Class representing the choices of possible vectorization patterns for the Pairwise Functors
Add a brief comment explaining what vectorization patterns are in a bit more detail. You can also reference the Arxiv paper (and later, once published, the actual paper - but lets not wait for that for the PR). I finally uploaded it to ArXiv so you can do this but might not be published there for a couple more days.

2025-12-03 13:09 UTC, SamNewcome commented on src/autopas/options/VectorizationPatternOption.h
> +     */
It would be good to have visual descriptions of these. E.g.

```suggestion
    /**
     * Interact one particle from the first list with the full vector length from the second list
     *
     * ---------------------------------
     * | i | i | i | i | i | i | i | i |
     * ---------------------------------
     * | j |j+1|j+2|j+3|j+4|j+5|j+6|j+7|
     *  --------------------------------
     */
```

2025-12-03 13:09 UTC, SamNewcome commented on src/autopas/options/VectorizationPatternOption.h
> +     */
And similar for the other patterns

2025-12-03 13:09 UTC, SamNewcome commented on src/autopas/options/VectorizationPatternOption.h
> +        {VectorizationPatternOption::pVecx1, "VectorLengthx1"},
```suggestion
        {p1xVec, "1xVectorLength"},
        {p2xVecDiv2, "2xVectorLengthDiv2"},
        {pVecDiv2x2, "VectorLengthDiv2x2"},
        {pVecx1, "VectorLengthx1"},
```

2025-12-03 13:09 UTC, SamNewcome commented on src/autopas/options/VectorizationPatternOption.h
I know we don't do this with other options, but we should probably make `_value` `const`. Then we don't need the default `_value` initialised to `-1`. As we don't provide setters for the option, there shouldn't be issues with this. We should also then delete the default constructor.

2025-12-03 13:09 UTC, SamNewcome commented on src/autopas/tuning/Configuration.cpp
> +    // Consequently, we need some sort of access to the functor
Do this ToDo.

Fyi, I wouldn't actually do this here in `Configuration` because you don't have access to the functor. There is another possibility to do this in `LogicHandler::isConfigurationApplicable`, where you have the functor - this is where we exclude a configuration e.g. if `newton3` is not allowed by the functor.

Potentially we should have the base `Functor` have some `allowedVecPatterns` method which allows you to check is a pattern is allowed. By default, for `PairwiseFunctor` this can be `p1xVec` so we don't have to make changes.

For triwise, potentially, we need a separate `TriwiseVectorizationPatternOption` which for now just includes a `3B_default` enum, which again the `TriwiseFunctor` has set by default. The idea would be to set this up either so that it is clear that triwise functors do not have different patterns (and to not confuse matters that giving them as a placeholder a pairwise pattern like `p1xVec` which doesn't make sense in the case that we have three lists), and to provide a possibility for adding this functionality to triwise functors in the future. I'm not sure whether a separate option class or some distinction within the existing option class makes more sense.

You may then run into issue #1032 (see my comment referenced in the issue where I provide more details).

It may therefore be that we need a fix to this issue before we can merge this branch in. Check by running e.g. the AVX functor with additional patterns than just `p1xVec`. If this is an issue, maybe do this in a separate PR.

2025-12-03 13:09 UTC, SamNewcome commented on tests/MPIParallelAutoPasTests/tests/tuning/selectors/tuningStrategy/MPIParallelizedStrategyTest.h
Maybe add one case where the configuration includes a pattern other than `p1xVec`

2025-12-03 13:09 UTC, SamNewcome commented on tests/MPIParallelAutoPasTests/tests/utils/AutoPasConfigurationCommunicatorTest.cpp
> +  EXPECT_EQ(size, 6 * 3);
```suggestion
  // There are 108 configurations in the Cartesian product, but only 18 of them are
  // valid.
  EXPECT_EQ(size, 18);
```
My understanding is that there's nothing special about vec patterns in this case, so I think its maybe confusing to single them out.

2025-12-03 13:09 UTC, SamNewcome commented on examples/md-flexible/CMakeLists.txt
> +option(MD_FLEXIBLE_FUNCTOR_HWY "Compile Highway Functor, which uses the best available SIMD instruction set supported by google highway." ON)
My suggestion is that we set the `AVX` and `SVE` functors to `OFF`, and by default, we use the HWY functor, because

- The HWY functor has the additional functionality of vector patterns.
- We probably want the HWY functor as the default anyway: we get AVX512 instructions, which is good for CoolMUC, SuperMUC, HSUper.
- It's slow to compile both the HWY and AVX or SVE functors.

2025-12-03 13:09 UTC, SamNewcome commented on examples/md-flexible/input/fallingDropWrapperFunctor.yaml
Remove this and all other new input files plus the bechmarks - I don't want to clutter the repository. We could keep one of the exploding cube scenarios (e.g. `Exploding_Cube_hwy.yaml` - you can drop the `_hwy` part of the name). Clean it up a bit and remove the deadcode.

Also, change the existing yaml input files (exploding liquid, falling drop, spinodial decomposition) to use the highway functor.

2025-12-03 13:09 UTC, SamNewcome commented on cmake/modules/autopas_vectorization.cmake
Let's change `AUTOPAS_USE_VECTORIZATION` to `AUTOPAS_USE_AUTOVEC`, so there's no confusion with manual vectorisation. 

I would also argue that we shouldn't actively support anything other than `-march=native`: the list for manually setting this is somewhat out of date and I don't care for maintaining it. The cases where `-march=native` is not suitable are somewhat niche (e.g., wanting to avoid AVX512 operations on hardware that technically supports them but not performantly). As we get better performance from manual vectorisation and highway gives us a performance portable option for this, I don't see a case where we really care about these cases. And there is nothing stopping the user from manually setting the architecture themselves.

2025-12-03 13:09 UTC, SamNewcome commented on cmake/modules/autopas_highway.cmake
Can you go through the CMake options from highway and see what we actually want to expose to the user and what we can make "advanced mode" options.

2025-12-03 13:09 UTC, SamNewcome commented on examples/md-flexible/src/configuration/CLIParser.cpp
> +          config.functorOption.value = MDFlexConfig::FunctorOption::lj12_6_HWY;
This needs to be above the previous `if`-clause, to avoid e.g. `lj_hwy` resulting in the autovec functor being used.

2025-12-03 13:09 UTC, SamNewcome commented on examples/md-flexible/src/configuration/CLIParser.cpp
> +      */
Remove deadcode

2025-12-03 13:09 UTC, SamNewcome commented on examples/md-flexible/src/configuration/MDFlexConfig.cpp
> +  // @todo filter vec patterns here to avoid non-HWY functors searching for patterns?
Remove. 

Btw, you could potentially do this to get around the problem #1022, but I would rather you just fix the issue.

2025-12-03 13:09 UTC, SamNewcome commented on examples/md-flexible/src/configuration/MDFlexConfig.cpp
> +      }
This should be removed -> I think this is old from when this was a separate option as opposed to a CMake flag

2025-12-03 13:09 UTC, SamNewcome commented on examples/md-flexible/src/configuration/MDFlexConfig.h
> +  enum class FunctorOption { none, lj12_6, lj12_6_AVX, lj12_6_SVE, lj12_6_Globals, lj12_6_HWY };
Remove "globals"

2025-12-03 13:09 UTC, SamNewcome commented on examples/md-flexible/src/configuration/MDFlexConfig.h
> +                                                      "lennard-jones-AVX lennard-jones-SVE lennard-jones-globals "
Remove globals

2025-12-03 13:09 UTC, SamNewcome commented on examples/md-flexible/src/configuration/YamlParser.cpp
> +          config.functorOption.value = MDFlexConfig::FunctorOption::lj12_6_HWY;
Move above previous if statement

2025-12-03 13:10 UTC, SamNewcome requested changes
There are some performance related suggestions. Imo, these aren't critical and don't have to be done this PR. We have our AutoPas internal meeting on Friday so I might discuss this with @thesamriel then, whether we want you to investigate this. For now, it would be good if you at least comment with your views on if you think they are good ideas, or meh, you think they are not worth investigating, or you don't know - don't spend too much time researching, just if your previous experience suggests something.

2025-12-04 10:45 UTC, SamNewcome commented on src/autopas/options/VectorizationPatternOption.h
> + * Class representing the choices of possible vectorization patterns for the Pairwise Functors
Here's the DOI: https://doi.org/10.48550/arXiv.2512.03565

2025-12-04 17:37 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  }
I did that, but only for this functor. Maybe we should do that for the others too at some point.

2025-12-04 17:38 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  constexpr int obtainFirstLoopRest(const int i, const int stop) {
I use `obtainILoopRemainderLength` now.

2025-12-05 07:42 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  }
Thanks. It would be good if you could also do this for the ATM HWY functor if you haven't already, but I wouldn't worry about AutoVec, AVX, and SVE.

2025-12-05 11:40 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +                             VectorDouble &y1, VectorDouble &z1, MaskDouble &ownedMaskI, const size_t restI) {
The problem here is that we later do a logical and with the `ownedMaskI` and the `cutoffMask` (double mask). With highway, logical operations can only be performed with the same mask types.
So we have two options:
1) Create double masks directly, as we do now. This is not so nice because it's not very intuitive why this is being done.
2) Create integer masks. Then we would have to cast the `cutoffMask` in the kernel. I don't know if this would have a negative impact on performance. Probably only a minor one.

2025-12-05 12:30 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +using MaskLong = decltype(highway::FirstN(tag_long, 2));
I did something very similar in my ATM Highway branch. If it is suitable, I could also incorporate it here, or we could do it when merging the ATM Highway branch.

2025-12-05 12:40 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    for (; j < (neighborList.size() & ~(_vecLengthDouble - 1)); j += _vecLengthDouble) {
I replaced it everywhere in the functor with more intuitive variants without the bit operations. I also added some comments.

2025-12-05 13:06 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +using MaskLong = decltype(highway::FirstN(tag_long, 2));
No I'm happy for this to wait for the ATM HWY branch

2025-12-05 13:24 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +                             VectorDouble &y1, VectorDouble &z1, MaskDouble &ownedMaskI, const size_t restI) {
Hmm okay. What about doing the casting from an integer mask to double mask _within this_ function? So the comparison operation is still done with integers. And then rather than casting the owned state to a double, which doesn't make much sense, you are casting an integer mask to a double mask which in my mind makes more sense (I guess more efficient as well to cast masks than numbers - on AVX512 I believe the masks are agnostic of the data type)

2025-12-05 15:34 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.h
> +  bool particleEqual(Molecule &p1, Molecule &p2);
I had to add a `const` version of `begin()` in `SoA.h`, but I think it's good to have that.

2025-12-05 15:51 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  // EXPECT_NEAR(ljFunctorAVX.getVirial(), ljFunctorHWY.getVirial(), tolerance) << "global virial";
After uncommenting, I first had to fix a small bug in the globals calculation with newton3 (this was a leftover from earlier, when uPot/virial was incorrectly multiplied by 0.5). The globals were completely off. But even after fixing it, I had to use a tolerance of 1e-7.

2025-12-05 15:51 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  double tolerance = 1e-8;
Currently, I even have to use 1e-7 to pass the test.

2025-12-05 16:28 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +    PPL.calculateMixingCoefficients();
After doing that, I had to reduce the tolerance again. I'm a little concerned that there might be a small bug in the functor somewhere. (problematic only with newton3)

2025-12-05 16:43 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +
I removed `patternsToString` and use `VectorizationPatternOption::getOptionNames()` instead. `patterns` vector is still there to be passed to the test cases in `INSTANTIATE_TEST_SUITE_P`.

2025-12-05 17:55 UTC, dmartin13 commented on src/autopas/options/VectorizationPatternOption.h
I’m not 100% sure, but the problem is that we often use the standard assignment operator from `Configuration`, such as `_currentOptimalConfig = configuration;`. However, this operator is deleted when we have the const member `_value`. I suspect that this will require a larger redesign, which we should perhaps do when we make all `_value` members const.

2025-12-08 08:42 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  // EXPECT_NEAR(ljFunctorAVX.getVirial(), ljFunctorHWY.getVirial(), tolerance) << "global virial";
Hmmm. I don't really know how much this is just background FP error, but it feels too high to me. In the AVX test we compare AVX to AutoVec with a tolerance of 1e-8. 

I would try to check it more thoroughly. E.g. does this occur for all patterns or just some?

2025-12-08 08:46 UTC, SamNewcome commented on src/autopas/options/VectorizationPatternOption.h
Okay, then I would just keep it the way it is for now

2025-12-08 16:59 UTC, dmartin13 commented on cmake/modules/autopas_vectorization.cmake
`AUTOPAS_USE_VECTORIZATION` has been changed to `AUTOPAS_USE_AUTOVEC`. Furthermore, only `march=native` is now actively supported.

2025-12-08 18:02 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      _shift6AoS = ParticlePropertiesLibrary<double, size_t>::calcShift6(epsilon24, sigmaSquare, _cutoffSquareAoS);
Apparently, you need the template arguments here because of calcShift6, otherwise the compiler complains.

2025-12-08 18:02 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      _shift6 = highway::Set(tag_double, ParticlePropertiesLibrary<double, size_t>::calcShift6(
Same here, without template arguments the compiler complains.

2025-12-09 10:31 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      _shift6AoS = ParticlePropertiesLibrary<double, size_t>::calcShift6(epsilon24, sigmaSquare, _cutoffSquareAoS);
Hmm okay. Then just leave them as they are

2025-12-10 18:31 UTC, thesamriel requested changes
I had some time to look a bit into highway itself, so there are some more comments

2025-12-10 18:31 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  explicit LJFunctorHWY(double cutoff, ParticlePropertiesLibrary<double, size_t> *particlePropertiesLibrary = nullptr)
I would then also change to `std::optional<std::reference_wrapper<...>>` in the constructor.

2025-12-10 18:31 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * @tparam reversed
```suggestion
   * @tparam vecPattern
```

2025-12-10 18:31 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  inline void fillIRegisters(const size_t i, const double *const __restrict xPtr, const double *const __restrict yPtr,
This function still needs documentation

2025-12-10 18:31 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      auto newFz = fz2 - fzCombinedExt;
```suggestion
      const VectorDouble fx2 = highway::LoadN(tag_double, &fx2Ptr[j], lanes);
      const VectorDouble fy2 = highway::LoadN(tag_double, &fy2Ptr[j], lanes);
      const VectorDouble fz2 = highway::LoadN(tag_double, &fz2Ptr[j], lanes);

      const auto newFx = fx2 - fxCombinedExt;
      const auto newFy = fy2 - fyCombinedExt;
      const auto newFz = fz2 - fzCombinedExt;
```

2025-12-10 18:31 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      const auto fzCombinedExt = highway::ZeroExtendVector(tag_double, fzCombined);
There are a couple places in the code, where I don't really understand why we need to do `ZeroExtendVector()`
For example, here we could do:
```cpp
const auto fxCombined = lowerFx + upperFx;

const int lanes = remainder ? rest : _vecLengthDouble / 2;
const auto fx2 = hw::LoadN(tag_double_half, &fx2Ptr[j], lanes);

const auto newFx = fx2 - fxCombined;
hw::StoreN(newFx, tag_double_half, &fx2Ptr[j], lanes);
```

Let me know if I'm missing something

2025-12-10 18:31 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +          const auto mask = overlapMasks[remainder ? rest : _vecLengthDouble / 2];
`overlapMasks` is an array of Maskvectors, right?
It is defined as `MaskDouble overlapMasks[_vecLengthDouble / 2];`
So for a vector length of 4 this would be 2 masks.

Here, if `remainder == false`, we do `overlapMasks[2]` which is out of bounds. Does this case just never happen?

2025-12-10 18:31 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +            const auto mask = overlapMasks[_vecLengthDouble / 2];
again, shouldn't this be out of bounds?

2025-12-10 18:31 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      const auto lowerFzAccExt = highway::ZeroExtendVector(tag_double, lowerFzAcc);
Similar as above, I'm not sure why we need `ZeroExtendVector`

2025-12-10 18:31 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    const auto cutoffDummyMask = highway::And(cutoffMask, dummyMask);
```suggestion
    const auto dummyMask =
        highway::And(ownedMaskI, highway::MaskFromVec(highway::ConvertTo(tag_double, ownedStateJLong)));
    const auto cutoffDummyMask = highway::MaskedLe(dummyMask, dr2, _cutoffSquared);
```

I think this should do the same thing and be slightly better performing.

2025-12-11 12:51 UTC, dmartin13 commented on src/autopas/tuning/Configuration.cpp
> +    // Consequently, we need some sort of access to the functor
Okay, I've done that. Unfortunately, it took me some time because during implementing I realized that the AutoTuner never tuned for vec patterns, but always used `p1xVec`. That has now been fixed, as well as all the tests that failed because of it.

Regarding the three-body interactions: I'm currently using `p1xVec` as the default. I'm not entirely satisfied with this myself, but my other ideas weren't also ideal. I tried using a base class `VectorizationPatternOptionBase`. This could possibly work, but it would require a larger restructuring in Autopas. I wasn't too happy with the subdivision into `VectorizationPatternOption` either, because then, for example, `getAllOptions()` also returns the 3-body patterns and the autotuner has to sort them out. Maybe we can do that in a separate PR.

Regarding the AVX functor, you have to set `p1xVec` explicitly, otherwise you'll encounter the problem you described. We should also solve this in a separate PR.

2025-12-11 14:32 UTC, dmartin13 commented on cmake/modules/autopas_highway.cmake
Okay, those are all the ones I found. To be honest, I don't think it's necessary to expose them to the user (maybe HWY_CMAKE_SSE2, HWY_CMAKE_ARM7, ...).

```
HWY_CMAKE_ARM7          OFF       "Set copts for Armv7 with NEON (requires vfpv4)?"
HWY_CMAKE_LSX           ON        "Add -mlsx flag?"
HWY_CMAKE_LASX          ON        "Add -mlasx flag?"
HWY_CMAKE_SSE2          OFF       "Set SSE2 as baseline for 32-bit x86?"
HWY_CMAKE_RVV           ON        "Set copts for RISCV with RVV?"
HWY_WARNINGS_ARE_ERRORS OFF       "Add -Werror flag?"
HWY_CMAKE_HEADER_ONLY   OFF       "Change to header-only?"
HWY_ENABLE_CONTRIB      ON        "Include contrib/"
HWY_ENABLE_EXAMPLES     ON        "Build examples"
HWY_ENABLE_INSTALL      ON        "Install library"
HWY_ENABLE_TESTS        ON        "Enable HWY tests"
HWY_TEST_STANDALONE     OFF       "Disable use of googletest"
HWY_CXX_STD_TGT_COMPILE_FEATURE   [cxx_std_17, cxx_std_14, cxx_std_11]
HWY_THREAD_FLAGS                  "-pthread"
HWY_THREAD_LIBS                   ${CMAKE_THREAD_LIBS_INIT})
HWY_SOURCES
HWY_TEST_SOURCES
HWY_FLAGS
HWY_LIBRARY_TYPE                  ["SHARED", "STATIC"]
HWY_LIBRARY_VERSION               "${CMAKE_PROJECT_VERSION}"
HWY_PC_FILES                      libhwy.pc
HWY_PC_DISABLE_FUTEX_CFLAGS       "-DHWY_DISABLE_FUTEX"
HWY_PC_WIN32_SYNCHRONIZATION_LIBS "-lsynchronization"
HWY_PC_HWY_TEST_CFLAGS            "-DHWY_TEST_STANDALONE=1"
HWY_PC_HWY_TEST_REQUIRES          "gtest"
HWY_SYSTEM_GTEST        OFF       "Use pre-installed googletest?"
HWY_TEST_FILES
HWY_TEST_LIBS                     hwy hwy_test
HWY_GTEST_LIBS
```

2025-12-11 15:23 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  explicit LJFunctorHWY(double cutoff, ParticlePropertiesLibrary<double, size_t> *particlePropertiesLibrary = nullptr)
I have implemented this. The only consequence is that we now have to use `return f(LJFunctorTypeHWY{cutoff, std::ref(particlePropertiesLibrary)});` instead of `return f(LJFunctorTypeHWY{cutoff, particlePropertiesLibrary});`, but I think that's okay.

2025-12-13 11:46 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    const auto cutoffDummyMask = highway::And(cutoffMask, dummyMask);
I had to adjust it slightly because in `highway::MaskFromVec(highway::ConvertTo(tag_double, ownedStateJLong))`, the `ownedStateJLong` isn't logically compared with `_ownedStateDummy`.

But this works now:

```
const auto dummyMask =
        highway::And(ownedMaskI, highway::Ne(highway::ConvertTo(tag_double, ownedStateJLong), _ownedStateDummy));
    const auto cutoffDummyMask = highway::MaskedLe(dummyMask, dr2, _cutoffSquared);
```

2025-12-13 17:19 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +          const auto mask = overlapMasks[remainder ? rest : _vecLengthDouble / 2];
Really good catch! Actually, I noticed that the `_overlapMasks` are declared but never initialized. However, this is not a problem because the code is only executed if `reversed=true`. `reversed=true` is only the case in `SoAFunctorSingle`, and `SoAFunctorSingle` does not use `pVecDiv2x2`, but only `p1xVec`, as you noted in [https://github.com/AutoPas/AutoPas/pull/972#discussion_r2542097681](). So I removed this dead code.

2025-12-14 14:52 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      const auto fzCombinedExt = highway::ZeroExtendVector(tag_double, fzCombined);
I modified it like this and it works.

2025-12-14 14:52 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +            const auto mask = overlapMasks[_vecLengthDouble / 2];
Similar

2025-12-14 16:13 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      fz2Ptr[j] -= highway::ReduceSum(tag_double, lowerFzExt);
The `ZeroExtendVector` operations have now been omitted, as well as the middle part:

```
if constexpr (reversed) {
	if (j > i - _vecLengthDouble / 2) {
	  const auto mask = overlapMasks[remainder ? rest : _vecLengthDouble / 2];
	  lowerFxExt = highway::IfThenElseZero(mask, lowerFxExt);
	  lowerFyExt = highway::IfThenElseZero(mask, lowerFyExt);
	  lowerFzExt = highway::IfThenElseZero(mask, lowerFzExt);
	}
}
```

(see: [https://github.com/AutoPas/AutoPas/pull/972#discussion_r2616424024]())

2025-12-14 16:13 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        fz2Ptr[j + 1] -= highway::ReduceSum(tag_double, upperFzExt);
similar (see: [https://github.com/AutoPas/AutoPas/pull/972#discussion_r2617283776]())

2025-12-14 16:34 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +    PPL.calculateMixingCoefficients();
I adjusted the test parameters slightly. On the one hand, I made the LJ parameters more varied, and on the other hand, I made the simulation box slightly larger. This prevents particles with higher sigma that are tightly packed together from generating high forces. Now I can use `1e-8` in all tests, as with AVX. I also went through the tests systematically again and looked at some code sections, but I couldn't find any bugs. I suspect it's due to FP inaccuracies when very large forces are generated.

2025-12-14 16:35 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +    double tolerance = 2e-8;
see [https://github.com/AutoPas/AutoPas/pull/972#discussion_r2617302046]()

2025-12-14 16:35 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  // EXPECT_NEAR(ljFunctorAVX.getVirial(), ljFunctorHWY.getVirial(), tolerance) << "global virial";
see [https://github.com/AutoPas/AutoPas/pull/972#discussion_r2617302046]()

It happens for all vecpatterns. It is only noticeable that the tests require a higher tolerance when mixing is enabled. However, this can probably be explained by the fact that the LJ values vary more here and are not set to 1.0.

2025-12-14 16:38 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  double tolerance = 1e-8;
see [https://github.com/AutoPas/AutoPas/pull/972#discussion_r2617302046]()

2025-12-14 16:39 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +    PPL.calculateMixingCoefficients();
see [https://github.com/AutoPas/AutoPas/pull/972#discussion_r2617302046]()

2025-12-14 16:39 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  // EXPECT_NEAR(ljFunctorAVX.getVirial(), ljFunctorHWY.getVirial(), tolerance) << "global virial";
see [https://github.com/AutoPas/AutoPas/pull/972#discussion_r2617302046]()

2025-12-14 16:39 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  }
see [https://github.com/AutoPas/AutoPas/pull/972#discussion_r2617302046]()

2025-12-14 16:39 UTC, dmartin13 commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  }
see [https://github.com/AutoPas/AutoPas/pull/972#discussion_r2617302046]()

2025-12-22 17:53 UTC, SamNewcome requested changes
Looks good. Only really very minor things left.

2025-12-22 17:53 UTC, SamNewcome commented on .github/workflows/TestSuites.yaml
> +
Why not just use `matrix.split`?

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +      if (!_PPLibrary.has_value()) {
```suggestion
      if (not _PPLibrary.has_value()) {
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   */
```suggestion
  /**
   * Checks whether the loop over i should be continued. This depends on the respective VectorizationPattern.
   *
   * @tparam reversed Whether iterating backwards over i.
   * @tparam vecPattern
   * @param i
   * @param vecEnd
   * @return true if the loop over i should be continued, else false.
   */
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * Calculates the step size depending on VectorizationPattern, by which i is decremented in the outer loop.
```suggestion
   * Calculates the step size by which i is decremented in the outer loop, depending on VectorizationPattern, .
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * Calculates the step size depending on VectorizationPattern, by which i is incremented in the outer loop.
```suggestion
   * Calculates the step size by which i is incremented in the outer loop, depending on VectorizationPattern.
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * Determines the remainder length that can't be vectorized in the loop over i.
Correct me if I'm wrong: it is vectorised, just that the vector registers cannot be fully filled.

```suggestion
   * Determines the number of registers filled in the case of a final, only partially filled, kernel call in the loop over i.
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * @return the remainder length that can't be vectorized in the loop over i.
```suggestion
   * @return the number of registers filled.
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   */
```suggestion
  /**
   * Checks whether the inner loop over j should be continued. This depends on the respective VectorizationPattern.
   *
   * @tparam vecPattern
   * @param i
   * @param j
   * @return  true if the inner loop over j should be continued, else false.
   */
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * Calculates the step size depending on VectorizationPattern, by which j is incremented in the inner loop.
```suggestion
   * Calculates the step size by which j is incremented in the inner loop, depending on VectorizationPattern, .
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * Determines the remainder length that can't be vectorized in the loop over j.
Please check this:
```suggestion
   * Determines the number of registers filled in the case of a final, only partially filled, kernel call in the loop over j.
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * @return the remainder length that can't be vectorized in the loop over j.
```suggestion
   * @return the number of registers filled.
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * @param restI Used in the case of the remainder loop
```suggestion
   * @param restI The number of lanes filled in case of a remainder loop.
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * @param rest Used in the case of the remainder loop
Similar to `fillIRegisters`

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        highway::And(ownedMaskI, highway::Ne(highway::ConvertTo(tag_double, ownedStateJLong), _ownedStateDummy));
I would do this similarly to in the `fillXRegisters` (or whichever function it was): Compare as a long, then rebind as a double mask.

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
>    for (size_t i = 0; i < cell1.size(); ++i) {
```suggestion
  for (size_t i = 0; i < std::min(cell1.size(), cell2.size()); ++i) {
```
Or make the above `EXPECT_EQ` an `ASSERT_EQ`

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +    if (!checkParticlesAreEqual(cell1._particles[i], cell2._particles[i])) {
```suggestion
    if (not checkParticlesAreEqual(cell1._particles[i], cell2._particles[i])) {
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +  return !anyNotEqual;
```suggestion
  return not anyNotEqual;
```

(Feel free to alternatively get rid of the double negation and make the flag `allEqual`)

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +      // pick some random particles to be marked as deleted
```suggestion
      // pick some arbitrary particles to be marked as deleted
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +      // pick some random particles to be marked as deleted
```suggestion
      // pick some arbitrary particles to be marked as deleted
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +      // pick some random particles to be marked as deleted
```suggestion
      // pick some arbitrary particles to be marked as deleted
```

2025-12-22 17:53 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +      // pick some random particles to be marked as deleted
```suggestion
      // pick some arbitrary particles to be marked as deleted
```

2025-12-22 17:53 UTC, SamNewcome commented on src/autopas/options/VectorizationPatternOption.h
> +     * | i | i | i |i+1|i+1|i+1|i+1|i+1|
```suggestion
     * | i | i | i | i |i+1|i+1|i+1|i+1|
```
I think that was my mistake haha

2025-12-22 17:53 UTC, SamNewcome commented on src/autopas/options/VectorizationPatternOption.h
> +     * | j | j | j |j+1|j+1|j+1|j+1|j+1|
```suggestion
     * | j | j | j | j |j+1|j+1|j+1|j+1|
```

2025-12-22 17:53 UTC, SamNewcome commented on tests/testAutopas/tests/tuning/AutoTunerTest.cpp
> +  //                        newton3 <=> noNewton3, 4 vecPattern)                 = 16
Only one vec pattern is allowed for VL(C)

2025-12-22 17:53 UTC, SamNewcome commented on tests/testAutopas/tests/tuning/AutoTunerTest.cpp
> +  //                        <=> noNewton3, 4 vecPattern)                 = 16
Similarly

2025-12-24 13:11 UTC, dmartin13 commented on .github/workflows/TestSuites.yaml
> +
Ah, thank you. The complicated `SplitFactor` calculation was a leftover from a previous version.

2025-12-24 13:11 UTC, dmartin13 commented on tests/testAutopas/tests/tuning/AutoTunerTest.cpp
> +  //                        newton3 <=> noNewton3, 4 vecPattern)                 = 16
Good catch! That was actually still a bug in the code because the autotuner generated too many valid configurations. I have now introduced `CompatibleVectorizationPattern`.

2026-01-08 08:45 UTC, SamNewcome requested changes
All good. Only some minor comment suggestions.

2026-01-08 08:45 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * @return the number of registers filled.
```suggestion
   * @return the number of lanes filled.
```
This was my terminology mistake, sorry!

2026-01-08 08:45 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +   * @return the number of registers filled.
```suggestion
   * @return the number of lanes filled.
```

2026-01-08 08:45 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    // conert to a double mask since we perform logical operations with other double masks in the kernel.
```suggestion
    // convert to a double mask since we perform logical operations with other double masks in the kernel.
```

2026-01-08 08:45 UTC, SamNewcome commented on src/autopas/containers/CompatibleVectorizationPattern.h
> +}
My concern with this is that this gets forgotten and somebody adds a new container that can only use `p1xVec`.

I would suggest just adding to `CONTRIBUTING.md` under "Adding a new Container" something like
```
* Check that `CompatibleVectorizationPattern::allCompatibleVectorizationPattern` is correctly set.
```
I think that this is good enough - at the end of the day, if this is incorrectly set, the only real issue is all the vectorisation pattern options get trailed, but under-the-hood simply do the same thing.

2026-01-23 10:36 UTC, SamNewcome commented
An update about this branch:

- I compared the HWY and AVX functors on an exploding liquid scenario, like the one in the Newcome et al. 2025 paper but scaled down. I ran it on HSUper - (Icelake architecture, supports 512-bit AVX3 instructions in addition to those used in the AVX functor). I use HWY only with the p1xVec pattern.
- I found HWY to perform ~20% slower.
- Even when compiling HWY with AVX3 disabled, forcing the use of the same 256-bit AVX instructions, this only made a marginal improvement (~2% faster).

I dug into why this might be:

We have almost double the number of load operations, specifically 88% more, (i.e., as measured with VTune) in the HWY version as the AVX version. So I looked into where we might do loading differently.

About 3/4 of the slowdown (i.e. ~15%) comes from setting the physics registers. In the AVX functor, we use `_mm256_set_pd`, which takes four arguments and sets each to one of the four lanes of the vector register. This looks like

```
epsilon24s = _mm256_set_pd(
    not remainderIsMasked or rest > 3 ? _PPLibrary->getMixing24Epsilon(*typeID1ptr, *(typeID2ptr + 3)) : 0,
    not remainderIsMasked or rest > 2 ? _PPLibrary->getMixing24Epsilon(*typeID1ptr, *(typeID2ptr + 2)) : 0,
    not remainderIsMasked or rest > 1 ? _PPLibrary->getMixing24Epsilon(*typeID1ptr, *(typeID2ptr + 1)) : 0,
    _PPLibrary->getMixing24Epsilon(*typeID1ptr, *(typeID2ptr + 0)));
sigmaSquareds = _mm256_set_pd(
    not remainderIsMasked or rest > 3 ? _PPLibrary->getMixingSigmaSquared(*typeID1ptr, *(typeID2ptr + 3)) : 0,
    not remainderIsMasked or rest > 2 ? _PPLibrary->getMixingSigmaSquared(*typeID1ptr, *(typeID2ptr + 2)) : 0,
    not remainderIsMasked or rest > 1 ? _PPLibrary->getMixingSigmaSquared(*typeID1ptr, *(typeID2ptr + 1)) : 0,
    _PPLibrary->getMixingSigmaSquared(*typeID1ptr, *(typeID2ptr + 0)));
```

Highway does not support this function, presumably because it would be hard to write a wrapper for this function that would work for an arbitrary number of lanes. So the highway version of this looks like

```
HWY_ALIGN std::array<double, _maxVecLengthDouble> epsilons{};
HWY_ALIGN std::array<double, _maxVecLengthDouble> sigmas{};
HWY_ALIGN std::array<double, _maxVecLengthDouble> shifts{};

for (int j = 0; j < (remainderIsMasked ? rest : 4); ++j) {
  epsilons[j] = _PPLibrary->getMixing24Epsilon(*typeID1ptr, *(typeID2ptr + j));
  sigmas[j] = _PPLibrary->getMixingSigmaSquared(*typeID1ptr, *(typeID2ptr + j));
  if constexpr (applyShift) {
    shifts[j] = _PPLibrary->getMixingShift6(*typeID1ptr, *(typeID2ptr + j));
  }
}

epsilon24s = _mm256_load_pd(epsilons.data());
sigmaSquareds = _mm256_load_pd(sigmas.data());
if constexpr (applyShift) {
  shift6s = _mm256_load_pd(shifts.data());
}
```
(i.e., the HWY code looks like this, but with HWY functions. I've not included that code because it is a little more complex due to `constexpr` branching for the different patterns.)

I.e., in HWY we fill a regular array scalar-ly, and then load it into a vector register. I don't totally know why this results in more load operations, but somehow this `_mm256_set_pd` can handle this way more efficiently than this HWY workaround can. But, it is not the operation itself that is more efficient, but the combination of this and the gets from the PPL.

I checked these findings by:

- Replacing all gets with `1.` (i.e., like no mixing but with the same operations). This reduces the slowdown to 5% and the number of load operations to only 5% more.
- Handicapping the AVX code by replacing its use of `_mm256_set_pd` with the workaround, but written with AVX instructions (i.e. the code snippet above). This reduces the slowdown to 6% and the number of load operations to only 6% more.

The latter shows that the workaround is responsible for both 3/4 of the slowdown and the vast majority of the additional load operations. The former shows that it is not specifically the use of `_mm256_set_pd`, but the combination of this and the gets from the PPL. It could even be that the slowdown was not seen by Luis because on a different architecture,e this is not handled so efficiently.

### Solutions

A year or so ago, I did a little exploration into removing the PPL and doing the mixing in the kernel itself. This had good performance in the functor benchmark with AVX512 but results were a little mixed in real use cases - but these results were really preliminary and I never finished this work. I want to return to this at some point - if we find that this is actually more performant in general, then HWY does not need this workaround. So I would suggest for now, we merge this into `master` rather than trying to fix this issue, as it could be we find that we don't need a fix for the workaround.

If we stick with the PPL, some alternative solutions could be

- We try to write our own wrapper for this function. But I worry this would be messy and defeat the purpose of using highway. This would also be probably rather difficult to write - we might need different wrappers for 4-lanes and 8-lanes that compile to scalar functions like the workaround in the case that we don't know we have this many lanes at compile time.
- We use gather instructions. This is probably the easiest solution, but I don't know how much it would close the performance gap.


### The remaining 1/4 of the problem

If we solved the above, we would only have a slowdown of about 5%. This is, IMO, much more acceptable. I did try to dig into why this was the case, comparing the HWY functor to the "handicapped" AVX functor. I found that the AVX functor makes much more use of the L1 cache - the memory-bounded stats showed that this almost entirely came from the L1 cache. On the other hand, for HWY, about 1/3rds of the L1 cache-boundedness became L2 cache-boundedness. So it seems that HWY makes worse use of the L1 cache. But I don't know why - as this is only a minor slow down, I will leave finding the exact cause of this for now.

### Going forward & questions

For now, I will just get the branch ready for merging. Some questions however: We changed CMake and the yaml files to use highway by default. Do we stick with this? For context, I found a 20% slowdown in the main scenario I investigated, but in another scenario this was as little as 3% and in another as much as 50%.

2026-01-23 13:08 UTC, thesamriel commented
I would assume that calculating mixing values directly in the Functor is better than the redirection via the PPL, especially for vectorized versions. So, in the bigger picture, I would vote for that.
But this would of course raise the question of whether we need the PPL at all and then this would be a bigger refactoring step. 

Regarding the other 1/4. How did you analyze the cache here? Maybe HWY fills up the instruction cache more through possible redirections. I don't know about the L1 cache structure on HSUper right now. If it's just the L1 data cache, I'm not sure what could cause the differences.

2026-01-23 14:43 UTC, SamNewcome commented
> I would assume that calculating mixing values directly in the Functor is better than the redirection via the PPL, especially for vectorized versions. So, in the bigger picture, I would vote for that. But this would of course raise the question of whether we need the PPL at all and then this would be a bigger refactoring step.

So the silly thing is I actually have a branch where I did this. But never merged it into master as I never completed the work. But I don't think reviving this would take too much work.

> Regarding the other 1/4. How did you analyze the cache here? Maybe HWY fills up the instruction cache more through possible redirections. I don't know about the L1 cache structure on HSUper right now. If it's just the L1 data cache, I'm not sure what could cause the differences.

The was with VTune's memory access collection.

For Highway:
[highway_memory_access.log](https://github.com/user-attachments/files/24823113/highway_memory_access.log)

For AVX with the handicap (i.e. loading mixing parameters the same way as HWY):
[avx_with_handicap_memory_access.log](https://github.com/user-attachments/files/24823120/avx_with_handicap_memory_access.log)

> Maybe HWY fills up the instruction cache more through possible redirections.

I think all wrapper instructions get inlined with their relevant instructions at compile time, so I'm not too sure about redirection costs. But it could be that we are doing some additional instructions which we don't do in the AVX version.

2026-02-10 17:40 UTC, thesamriel commented
I find it difficult to tell whether the performance difference is actually coming from highway or maybe the implementational differences between this version and the AVX version could come into play as well.
It's a bit tricky to really compare the whole flow due to the extracted functions with the `vecpattern` differentiations. 
If you want to explore this in more detail, I think it would be good to replicate the AVX Functor with highway instructions as close as possible. 
(Not necessarily for this PR)

2026-02-11 10:49 UTC, thesamriel requested changes
Looks good, mostly comments on tidyness.
It might be nice to mention somewhere that only the LJ highway functor supports the vector patterns and LJFunctorAVX/SVE don't. Not sure where the  best place for this is, though.

2026-02-11 10:49 UTC, thesamriel commented on .github/CONTRIBUTING.md
> +  * Containers which use SoAFunctorVerlet, or otherwise only support the traditional 1xVecLength vectorization pattern, should specify this.
Maybe phrase it the other way around?
`SoAFunctorVerlet` is implemented only for the traditional 1xVecLength, so this should be specified for containers using this functor method.

2026-02-11 10:49 UTC, thesamriel commented on src/autopas/tuning/tuningStrategy/BayesianClusterSearch.cpp
> +      _vecPatternOptions(allowedVecPatternOptions.begin(), allowedVecPatternOptions.end()),
I think this should go beneath the N3 initialization.
(There's a compiler warning on the initialization order here)

2026-02-11 10:49 UTC, thesamriel commented on cmake/modules/autopas_highway.cmake
> +    FetchContent_Populate(autopas_highway)
`FetchContent_Populate()` is (going to be) deprecated.
I think this should be the correct replacement:
```
set(HWY_ENABLE_TESTS OFF CACHE BOOL "Disable tests")
FetchContent_MakeAvailable(autopas_highway)

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +                                   const unsigned int j, const unsigned int restI, const unsigned int restJ) {
`j`, the function parameter seems to not be used inside the function. All usages of j seem to be redefinitions.

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        _PPLibrary{particlePropertiesLibrary} {
The ordering is not quite correct.
Also, `_potentialEnergySum` and `_aosThreadData` are already zero initialized at their declaration.
For consistency, I would probably zero initialize all of these at declaration and remove them from the constructor

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    return std::find(_vecPatternsAllowed.begin(), _vecPatternsAllowed.end(), vecPattern) != _vecPatternsAllowed.end();
```suggestion
    return std::ranges::find(_vecPatternsAllowed, vecPattern) != _vecPatternsAllowed.end();
```
I like ranges :D

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +                                   const unsigned int j, const unsigned int restI, const unsigned int restJ) {
Also, the function can be marked `const`

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  bool isVecPatternAllowed(const VectorizationPattern vecPattern) override final {
```suggestion
  bool isVecPatternAllowed(const VectorizationPattern vecPattern) final {
```

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  template <bool newton3>
```suggestion
```
doesn't use `newton3`

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  // flag to indicate wether post processing has been performed.
```suggestion
  // flag to indicate whether post-processing has been performed.
```

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  inline void handleILoopBody(
Could you add a brief description?
I don't need the list of all parameters, just one comment on what the function is for would be nice :D

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    }
Depending on the scenario, it can also be better not to have this if-statement.
Maybe `[[unlikely]]` is helpful?
Just ideas though, no must.

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  template <bool remainder, bool reversed, VectorizationPattern vecPattern>
```suggestion
  template <bool remainder, VectorizationPattern vecPattern>
```

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.h
> +                                           const bool useUnalignedViews, const VectorizationPattern pattern);
```suggestion
  void testLJFunctorvsLJFunctorHWYTwoCells(bool newton3, bool doDeleteSomeParticles,
                                           bool useUnalignedViews, VectorizationPattern pattern);
```

To quote clang-tidy:
"const-qualification  of parameters only has an effect in function definitions"
Also in the other functions

2026-02-11 10:49 UTC, thesamriel commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +TEST_P(LJFunctorTestHWY, testLJFunctorVSLJFunctorHWYAoS) {
To be fair, the test names are fairly clear, but I think we wanted to consistently document the tests

2026-02-11 11:55 UTC, SamNewcome commented
> It might be nice to mention somewhere that only the LJ highway functor supports the vector patterns and LJFunctorAVX/SVE don't. Not sure where the best place for this is, though.

Done in 7e64ebd8

I added something about this to `AllOptions.yaml` and all the functor classes. It is not tragic if other patterns are provided with functors that don't support them - these configurations are simply rejected.

2026-02-11 12:16 UTC, SamNewcome commented on cmake/modules/autopas_highway.cmake
> +    FetchContent_Populate(autopas_highway)
Good catch. Done in c212cdff

2026-02-11 12:48 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    }
You may be correct, but my role in this PR is really to just get it merged rather than performance optimise. 

I agree that this may have strong benefits, but I do not expect to see a clear always always-present benefit of either removing this or setting it to `[[unlikely]]`, and I expect cases where this is harmful. A cell-cell corner interaction has a hit rate of about 2%. For edges this is about 8%. In these cases, this is not necessarily so unlikely. I definitely recall Fabio finding positive benefit of this branch. This may be something we can tune as another vectorisation setting.

-> In short, lets not do this now but I agree its interesting and we can maybe make it a tunable parameter.

2026-02-11 12:55 UTC, SamNewcome commented on .github/CONTRIBUTING.md
> +  * Containers which use SoAFunctorVerlet, or otherwise only support the traditional 1xVecLength vectorization pattern, should specify this.
Done in 9ac15da3

2026-02-11 12:56 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +                                   const unsigned int j, const unsigned int restI, const unsigned int restJ) {
Done in cbb393e4

2026-02-11 12:56 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +        _PPLibrary{particlePropertiesLibrary} {
Done in cbb393e4

2026-02-11 12:56 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    return std::find(_vecPatternsAllowed.begin(), _vecPatternsAllowed.end(), vecPattern) != _vecPatternsAllowed.end();
Done in cbb393e4

2026-02-11 12:56 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  bool isVecPatternAllowed(const VectorizationPattern vecPattern) override final {
Done in cbb393e4

2026-02-11 12:57 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  template <bool newton3>
Done in cbb393e4

2026-02-11 12:57 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  // flag to indicate wether post processing has been performed.
Done in cbb393e4

2026-02-11 12:58 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  inline void handleILoopBody(
Done in cbb393e4 - all the pointer parameters I left out from the description

2026-02-11 12:58 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  template <bool remainder, bool reversed, VectorizationPattern vecPattern>
Done in cbb393e4

2026-02-11 12:59 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.h
> +                                           const bool useUnalignedViews, const VectorizationPattern pattern);
Done in cbb393e4 (left the `const` object parameters in later functions, I'm not sure removing this from the declaration works)

2026-02-11 13:16 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> +TEST_P(LJFunctorTestHWY, testLJFunctorVSLJFunctorHWYAoS) {
No I agree. Done in cbb393e4

2026-02-14 12:40 UTC, thesamriel approved these changes

2026-03-27 08:21 UTC, SamNewcome commented
I have also in this branch now fixed #1008

2026-05-29 11:24 UTC, thesamriel requested changes

2026-05-29 11:24 UTC, thesamriel commented on .github/CONTRIBUTING.md
> +* Check [`CompatibleVectorizationPattern::allCompatibleVectorizationPattern()`](...) is correct.
This is missing the link I think

2026-05-29 11:24 UTC, thesamriel commented on examples/md-flexible/CMakeLists.txt
> +        $<$<BOOL:${MD_FLEXIBLE_FUNCTOR_HWY}>:MD_FLEXIBLE_FUNCTOR_HWY>
Can you move it 2 lines up for consistency?

2026-05-29 11:24 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    VectorDouble shift6s = highway::Undefined(tag_double);
In the case of `applyShift` being false, `shift6s` stays undefined, but is still added to the potential energy later. initialize it to 0 instead?

2026-05-29 11:24 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    // ownedStates2Tmp is int64_t because we can directly use static_case on the individual elements below, unlike other
`static_cast`

2026-05-29 11:24 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    // functors where we have to resort to unsafe reinterpret_cast
Why do we have to use `reinterpret_cast` in the other functors?

2026-05-29 11:24 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  template <bool newton3>
Can remove the newton3 template here as it is not used

2026-05-29 11:24 UTC, thesamriel commented on src/autopas/options/VectorizationPatternOption.h
> +    p2xVecDiv2,
What happens if you compile HWY functor on a machine without vector instructions?
Would highway give a compiler error? Or would it be compiled for a 'single-lane vector', which would be problematic with these vector patterns?

2026-05-29 11:24 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +                                     double *const __restrict fz2Ptr, const size_t i, const size_t j,
`i` is not used and could be removed

2026-05-29 11:24 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    _aosThreadData[threadnum].virialSum[0] += globals[0];
Why have this intermediate `std::array` here?
Could just do `_aosThreadData[threadnum].virialSum[0] += highway::ReduceSum(tag_double, virialSumX);` I'd say.

2026-05-29 11:24 UTC, thesamriel commented on examples/md-flexible/src/Simulation.cpp
> +  _autoPasContainer->setAllowedVecPatterns(_configuration.vecPatternOptions.value,
set it also for triwise, even if it's not yet supported, because it's already added to the search space later

2026-05-29 11:24 UTC, thesamriel commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> + */
All functions are documented twice, in the header and cpp. One place should be enough

2026-05-29 11:38 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    // functors where we have to resort to unsafe reinterpret_cast
Because we have to reinterpret ownership state as an integer

2026-05-29 11:54 UTC, SamNewcome commented on src/autopas/options/VectorizationPatternOption.h
> +    p2xVecDiv2,
In theory HWY compiles on non vector instructions. I don't know how this would behave in that case. But I'm not aware of any machine which we might want to run on not supporting at least two lanes. And anwsering this would be some work and as this PR had already been approved, I really just want to focus on anything thrown up between then and now (i.e. the recent few commits changing CI and CMake).

2026-05-29 12:07 UTC, SamNewcome commented on examples/md-flexible/src/Simulation.cpp
> +  _autoPasContainer->setAllowedVecPatterns(_configuration.vecPatternOptions.value,
I'd rather not implement this because it wasn't a feature in the already approved version of this PR. The only reason this PR wasn't merged back then was because there were updates to the master and resulting issues with the CI and CMake.

This would also not be so trivial. The current vector patterns don't make much sense for 3B and you would probably need new 3B patterns. I believe when David was working on the ATM HWY branch we discussed using 1xVec as a palceholder for now.

2026-05-29 12:14 UTC, SamNewcome commented on .github/CONTRIBUTING.md
> +* Check [`CompatibleVectorizationPattern::allCompatibleVectorizationPattern()`](...) is correct.
Done in 305cbeec

2026-05-29 12:14 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    VectorDouble shift6s = highway::Undefined(tag_double);
Done in 305cbeec

2026-05-29 12:14 UTC, SamNewcome commented on examples/md-flexible/CMakeLists.txt
> +        $<$<BOOL:${MD_FLEXIBLE_FUNCTOR_HWY}>:MD_FLEXIBLE_FUNCTOR_HWY>
Done in 305cbeec

2026-05-29 12:14 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    // ownedStates2Tmp is int64_t because we can directly use static_case on the individual elements below, unlike other
Done in 305cbeec

2026-05-29 12:15 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +  template <bool newton3>
Done in 305cbeec

2026-05-29 12:15 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +                                     double *const __restrict fz2Ptr, const size_t i, const size_t j,
Done in 305cbeec

2026-05-29 12:15 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    _aosThreadData[threadnum].virialSum[0] += globals[0];
Done in 305cbeec

2026-05-29 12:16 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/tests/singleSiteTests/LJFunctorTestHWY.cpp
> + */
Done in 305cbeec

2026-05-29 15:19 UTC, thesamriel commented on src/autopas/options/VectorizationPatternOption.h
> +    p2xVecDiv2,
Yeah, this was more of a question to understand, no need to assure of this now.

2026-05-29 15:34 UTC, thesamriel commented on examples/md-flexible/src/Simulation.cpp
> +  _autoPasContainer->setAllowedVecPatterns(_configuration.vecPatternOptions.value,
I didn't mean to implement it for triwise. It just felt odd, that later we create the triwise search space for all vector patterns.
I guess the other configs are thrown out later during the simulation when doing the `functor.supportsVecPattern` check, which is not a huge overhead. 
All good then

2026-05-29 15:59 UTC, thesamriel commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    // functors where we have to resort to unsafe reinterpret_cast
Okay, apparently because when casting the pointers we need reinterpret, got it!

2026-05-29 15:59 UTC, thesamriel approved these changes

2026-06-01 07:12 UTC, SamNewcome commented on examples/md-flexible/src/Simulation.cpp
> +  _autoPasContainer->setAllowedVecPatterns(_configuration.vecPatternOptions.value,
Yeah, I get what you mean. I guess longer term we would have a different list of vec pattern options for 3B. I'd probably say that once we have that we make a separate setter.

2026-06-01 07:18 UTC, SamNewcome commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorHWY.h
> +    // functors where we have to resort to unsafe reinterpret_cast
Yeah, sorry I didn't explain well. This is imo, something quite easy to break because you are not doing any actual conversion but simply pretending that it is a integer. I think in most compilers this should work, but there are no guarantees and if we were to change the underlying type of the ownership state to e.g. a different integer type with less bytes, it would probably break. Because here we are casting the actual values and not pointers, we don't have to deal with this.

2026-06-01 07:22 UTC, SamNewcome approved these changes

2026-06-01 07:22 UTC, merged