AoS Remiander Traversal
AutoPas/AutoPas pull request #983
Opened 2024-12-06 17:20 UTC by FG-TUM

# Description

The remainder traversal for 2B always used AoS AND SoA functor calls, forcing the user to implement both. This is potentially problematic / annoying (see LADDS).

This PR introduces a mechanic that SoA is only used if the current configuration asks for it. Otherwise only AoS is used.

## ~Related Pull Requests~

## ~Resolved Issues~

# How Has This Been Tested?

- [x] Extended existing tests to cover all data layouts 66e1f67d479fba8e6cb7210a6d5df3e9ba5851b3

2024-12-06 17:28 UTC, FG-TUM commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctor.h
> -      const int threadnum = autopas::autopas_get_thread_num();
This was redundant as it shadows the same variable defined at the start of the function.

2024-12-06 17:28 UTC, FG-TUM commented on applicationLibrary/molecularDynamics/molecularDynamicsLibrary/LJFunctorAVX.h
> -  template <bool newton3>
This was unused

2024-12-11 15:35 UTC, FG-TUM commented on src/autopas/LogicHandler.h
> +void LogicHandler<Particle>::remainderHelperBufferBufferSoA(PairwiseFunctor *f,
Things one only notices when not using IDE search functions to navigate the code :stuck_out_tongue_winking_eye: 
-> 394adfa4c

2024-12-11 15:37 UTC, FG-TUM commented
> I wonder if it would make sense at some point to outsource the remainder traversal to a separate class/file, since almost half of LogicHandler.h is remainder traversal logic.

Yes, I felt the same way when I wrote this. Especially now that there is also the 3Body stuff. We should do this but in a separate PR after this one is merged.

2024-12-11 17:02 UTC, thesamriel approved these changes

2024-12-12 08:18 UTC, SamNewcome requested changes
A couple minor commenting changes

2024-12-12 08:18 UTC, SamNewcome commented on src/autopas/LogicHandler.h
> +      const auto j = (i + jj) % particleBuffers.size();
Briefly describe the purpose of this

2024-12-12 08:18 UTC, SamNewcome commented on src/autopas/LogicHandler.h
> +        // For buffer interactions where bufferA == bufferB we can always enable newton3. For all interactions between
Remove the first sentence

2025-01-20 16:19 UTC, FG-TUM commented on src/autopas/LogicHandler.h
> +      const auto j = (i + jj) % particleBuffers.size();
fixed -> aa40a2a

2025-01-20 16:19 UTC, FG-TUM commented on src/autopas/LogicHandler.h
> +        // For buffer interactions where bufferA == bufferB we can always enable newton3. For all interactions between
fixed -> aa40a2a

2025-01-30 07:52 UTC, SamNewcome approved these changes

2025-01-30 21:24 UTC, merged